### ISSUE TITLE
Update to ^3.0.0 broke built: "Invalid configuration"

### ISSUE THREAD

**Issue by damianobarbati** [gajus/babel-plugin-react-css-modules#104]
Error:
```
Module build failed: Error: /Users/damz/Desktop/quant01/apps/user/app.js: Invalid configuration
    at PluginPass.Program (/Users/damz/Desktop/quant01/node_modules/babel-plugin-react-css-modules/dist/index.js:185:17)
    at newFn (/Users/damz/Desktop/quant01/node_modules/babel-traverse/lib/visitors.js:276:21)
```

In package.json:
`"babel-plugin-react-css-modules": "^3.0.0",`

In package.json:
```
    "babel": {
        "presets": [
            [
                "env",
                {
                    "targets": {
                        "browsers": [
                            "chrome 54",
                            "safari 9",
                            "firefox 50",
                            "edge 12",
                            "explorer 11"
                        ]
                    },
                    "modules": false,
                    "useBuiltIns": true,
                    "debug": true
                }
            ],
            "stage-0",
            "react"
        ],
        "plugins": [
            "transform-decorators-legacy",
            "transform-class-properties",
            [
                "react-css-modules",
                {
                    "filetypes": {
                        ".scss": "postcss-scss"
                    }
                }
            ]
        ]
    },
```

webpack.config.js
```
        },{
            test: /\.(css|scss|sass)$/i,
            loader: ExtractTextPlugin.extract({
                use: [{
                    loader: 'css-loader',
                    options: {
                        modules: true,
                        importLoaders: 2,
                        camelCase: true,
                        localIdentName: '[name]-[local]',
                        minimize: process.env.NODE_ENV === 'development' ? false : { presets: 'default' },
                        sourceMap: true,
                    },
                },{
                    loader: 'postcss-loader',
                    options: {
                        plugins: [
                            postcssAutoprefixer({ browsers: config.browserslist }),
                        ],
                        sourceMap: true,
                    },
                },{
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true,
                    },
                }]
            }),
        },{
```

**Comment by musicalshore** [comment]
I'm having a similar issue when I run Jest, but I think with your config you should now be passing an object to configure `postcss-scss` syntax. I believe this was a breaking change.

```
"filetypes": {
  ".scss": {
    "syntax": "postcss-scss"
  }
}
```

**Comment by musicalshore** [comment]
I added my postscss plugins from `postcss.config.js` to the `fileTypes` property and it's working now.

`{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["last 2 versions", "last 2 ie versions", "last 3 safari versions"]
      },
      "debug": false
    }],
    "react"
  ],
  "plugins": [
    "transform-class-properties",
    ["react-css-modules", {
      "filetypes": {
        ".scss": {
          "syntax": "postcss-scss"
        }
      },
      "context": "src",
      "exclude": "node_modules",
      "webpackHotModuleReloading": true
    }],
    "transform-object-rest-spread",
    "jsx-control-statements"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        ["react-css-modules", {
          "filetypes": {
            ".scss": {
              "syntax": "postcss-scss",
              "plugins": [
                "postcss-import",
                "autoprefixer"
              ]
            }
          },
          "webpackHotModuleReloading": false,
          "generateScopedName": "[local]"
        }]
      ]
    },
    "development": {
      "plugins": [
        "react-hot-loader/babel"
      ]
    }
  }
}
`

**Comment by damianobarbati** [comment]
Thanks @musicalshore it's working now!
Anyway I didnt need to move the plugins section: how am I supposed to convert this into json?

```
                    loader: 'postcss-loader',
                    options: {
                        plugins: [
                            postcssAutoprefixer({ browsers: config.browserslist }),
                        ],
                        sourceMap: true,

```
