### ISSUE TITLE
Cannot react property 'name' of undefined

### ISSUE THREAD

**Issue by PCreations** [gajus/babel-plugin-react-css-modules#11]
When using spread operator  (and maybe other attribute that not might have a `name` property) to pass `props` from parent to children, the plugin fails since `JSXSpreadAttribute` does not have a `name` attribute, thus throwing an error when attempting to read the `name` property of this `undefined` value.

**Comment by PCreations** [comment]
Oops, duplicate of #7

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/babel-plugin-react-css-modules/pull/12. Thank you @PCreations
