### ISSUE TITLE
keyword select requires $data option

### ISSUE THREAD

**Issue by Igor-Vuk** [gajus/babel-plugin-react-css-modules#111]
After I updated to version 3.1.0 from 2.8.0 I keep getting this message in console everytime I run building process with webpack.
`keyword select requires $data option`

I don't have and select or option tags in code.

**Comment by apennell** [comment]
After I ran build, I started getting that as well.

**Comment by OscarBarrett** [comment]
It's coming from `ajv-keywords`. Some discussion here: https://github.com/epoberezkin/ajv-keywords/issues/17
