### ISSUE TITLE
if I use PostCSS and the files of the CSS in my extension .pcss?

### ISSUE THREAD

**Issue by hazratgs** [gajus/babel-plugin-react-css-modules#117]
Greetings friends, very cool plug-in, but how can I be, if I use PostCSS and the files of the CSS in my extension .pcss?
Here are my configurations: [webpack.conf](https://github.com/hazratgs/react-foundation/tree/master/webpack) and [.babelrc](https://github.com/hazratgs/react-foundation/blob/master/.babelrc)
Tell me how to connect it correctly?

**Comment by gajus** [comment]
There is `filetypes` configuration.

Refer to https://github.com/gajus/babel-plugin-react-css-modules#configuration.
