### ISSUE TITLE
Not working in production

### ISSUE THREAD

**Issue by dsslimshaddy** [gajus/babel-plugin-react-css-modules#120]
This works fine in development environment. But in production its not working.

I tried 
```
import styles from './style.css';

...
<div className={styles['mystyle']}></div> // this works
<div styleName={'mystyle'}></div> // this dosent no class is formed.
```

my `.babelrc`

```
{
  "plugins": [
    ...
    [
      "react-css-modules", {
        "generateScopedName": "[name]-[local]-[hash:base64:5]",
        "webpackHotModuleReloading": true
      }
    ]
  ],
...
}

```

Also to be noted in both envs (dev and prod) the `style.css` is formed with proper declarations. only that the components with `styleName` are not getting the `className`

**Update** : I noticed this happening only while i have a `transform-react-inline-elements` plugin in `.babelrc`

**Comment by gajus** [comment]
> Update : I noticed this happening only while i have a transform-react-inline-elements plugin in .babelrc

`babel-plugin-react-css-modules` needs to be executed before `transform-react-inline-elements`.

**Comment by mqklin** [comment]
This should be in READme
