### ISSUE TITLE
Error: Cannot read property 'handleMissingStyleName' of undefined

### ISSUE THREAD

**Issue by ftripier** [gajus/babel-plugin-react-css-modules#121]
https://github.com/gajus/babel-plugin-react-css-modules/blob/578b417ef66e4f0c8f6ec29277dbd3749b7fe1f5/src/getClassName.js#L66

It seems like sometimes options aren't passed in to this function. We ran into the bug listed in the title on a namespaced style name called "PricingStyles.ControlledPricing".

**Comment by gajus** [comment]
Thank you for reporting.
