### ISSUE TITLE
Nested scss files don't resolve

### ISSUE THREAD

**Issue by daviddelusenet** [gajus/babel-plugin-react-css-modules#122]
Hi,

Currently I've a React component called `Case`. In this component I'm including my `Case` styles like this:

```
import CaseStyles from './Case.scss';
```

These are the contents of the `Case.scss` file:

```
.Case {
  overflow: hidden;
}
```

I use the `Case` class like this:

```
<div styleName="Case"></div>
```

And this works great! But now the trouble starts: I want to add some layout styles to my `Case` component. I added the following import to the `Case.scss` file:

```
@import './Test';

.Case {
  overflow: hidden;
}
```

Then when I log my `CaseStyles` variable I get the following object:

```
{Test: "Test___1JnZR", Case: "Case___3btcF"}
```

So far so good! But then I add my class `Test` like this:

```
<div styleName="Test"></div>
```

And I get the following error:

```
Module build failed: Error: /Users/lusenet/Development/momkai-com-placeholder/src/react/src/app/pages/Case/Case.js: Could not resolve the styleName 'Test'.
```

Shouldn't this be working? Thanks in advance!

**Comment by DylanVann** [comment]
Yeah I can't seem to make this work with any sort of importing within the `css` or `scss` files either. This seems like a common use case.

**Comment by Mike-Now** [comment]
@daviddelusenet What is the content of the file Test.scss? I can't replicate this error.

**Comment by hinok** [comment]
I know that it's quite old issue but it looks exactly the same as https://github.com/gajus/babel-plugin-react-css-modules/issues/202

I provided solution and explanation there: https://github.com/gajus/babel-plugin-react-css-modules/issues/202#issuecomment-461667443
