### ISSUE TITLE
Upgrade version of PostCSS

### ISSUE THREAD

**Issue by max-mykhailenko** [gajus/babel-plugin-react-css-modules#123]
Please upgrade version of `postcss` to 6. 
Now I have error occurs when used newer version of postcss plugin and old postcss.
https://github.com/postcss/postcss-nested/issues/54

**Comment by vladimirvolek** [comment]
I cannot use this module just because of this :(

**Comment by domehead100** [comment]
Is this resolved by [v3.3.2](https://github.com/gajus/babel-plugin-react-css-modules/tree/v3.3.2)?

**Comment by gajus** [comment]
Yes

**Comment by max-mykhailenko** [comment]
Thank you guys!
