### ISSUE TITLE
Usage with React Storybook

### ISSUE THREAD

**Issue by hegelstad** [gajus/babel-plugin-react-css-modules#124]
Hey community.

I wonder if anyone have been able to use babel-plugin-react-css-modules with React Storybook.

I have been trying to get it to work, but with no success so far.

I am using LESS as well, with less-loader chained.

`ModuleBuildError: Module build failed: Error: /src/Checkbox/index.js: Cannot use styleName attribute without importing at least one stylesheet.`

**Comment by gajus** [comment]
> ModuleBuildError: Module build failed: Error: /src/Checkbox/index.js: Cannot use styleName attribute without importing at least one stylesheet.

The error says whats the problem.

**Comment by hegelstad** [comment]
I figured.

Do you have an example on how the babel config should look like when using plugin to read less syntax?

I currently have 
`{
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: ['es2015', 'react'],
                            plugins: [
                                [
                                    'react-css-modules',
                                    {
                                        'filetypes': {
                                            '.less': 'postcss-less'
                                        }
                                    }
                                ]
                            ]
                        }
                    }
                ]
            },`
