### ISSUE TITLE
Limitation over react-css-modules

### ISSUE THREAD

**Issue by James2516** [gajus/babel-plugin-react-css-modules#126]
> babel-plugin-react-css-modules is not a drop-in replacement and does not cover all the use cases of react-css-modules.

What are all these use cases? Is [this](https://github.com/gajus/babel-plugin-react-css-modules#limitations) the only limitation (compared to react-css-modules)?

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/96
