### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by IanVS** [gajus/babel-plugin-react-css-modules#128]
If `undefined` or `null` is passed to `styleName`, an error will be thrown from [this line](https://github.com/gajus/babel-plugin-react-css-modules/blob/5aabe537ddc96d8a3f792b679c56a3b03c2c5c6f/src/getClassName.js#L72).  There should probably be a check against falsey values, and the plugin should not create a `className` if the check fails.

**Comment by douglasjunior** [comment]
Same here.
