### ISSUE TITLE
Error with classnames package

### ISSUE THREAD

**Issue by xDae** [gajus/babel-plugin-react-css-modules#13]
Trying the babel plugin with the [classnames](https://github.com/JedWatson/classnames) package im getting errors:

<img width="568" alt="captura de pantalla 2016-12-14 a las 17 48 23" src="https://cloud.githubusercontent.com/assets/6037190/21191658/29cdf8e4-c226-11e6-8927-17bc73e282b1.png">

the Button Component is so easy:

```javascript
import React, { PropTypes } from 'react';
import classNames from 'classnames';

import './button.scss';

const Button = ({ className, href, type, alt, children, onClick }) => {
  var btnClass = classNames('button', className, {
    'default': type === 'default',
    'alt': type === 'alt'
  });

  return (
    <button
      styleName={btnClass}
      onClick={onClick}
    >
      {children}
    </button>
  );
};

export default Button;
```

**Without** the classname package its working fine:

```javascript
import React, { PropTypes } from 'react';

import './button.scss';

const Button = ({ className, href, type, alt, children, onClick }) => {
  return (
    <button
      styleName="button default"
      onClick={onClick}
    >
      {children}
    </button>
  );
};

export default Button;
```

**Comment by PCreations** [comment]
It's because the code generated doesn't escape hypens, thus throwing syntax error. You can see the issue #14 for more information and this [pull request](https://github.com/gajus/babel-plugin-react-css-modules/pull/12) for a possible workaround.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/babel-plugin-react-css-modules/pull/12. Thank you @PCreations and @xDae .
