### ISSUE TITLE
Not working with already compiled jsx?

### ISSUE THREAD

**Issue by Sprinter100** [gajus/babel-plugin-react-css-modules#131]
I'm using TypeScript and all of the .ts and .tsx files are compiled by typescript compiler. In my tsconfig.json file there is "jsx": "react" field, so the typescript compiles jsx tags as well.
Webpack is working with already compiled .js files and it seems that react-css-modules plugin doesn't recognize "styleName" field in compiled React tags. Is this intentional or is it a bug?

**Comment by gajus** [comment]
It is intentional. I don't see an easy way to workaround this.

**Comment by amarinov** [comment]
@gajus It would be helpful if you put that in the README.  Thanks.
