### ISSUE TITLE
Is there codemod to do the syntax convertion?

### ISSUE THREAD

**Issue by NE-SmallTown** [gajus/babel-plugin-react-css-modules#134]
Currently if we want to use this plugin in a previous project, we have to convert all `className` to `styleName`(assume we have used css-modules before), use something like `className=\{styles\.(.*)} -> styleName={`$1`}` in any IDE or custom script/shell to do this, but you know that is not safe and may miss some cases(e.g. we use classnames library or the `className` is not simple `styles.xxx`).

So, could we implement a babel-plugin to do the syntax convertion(a new repo or embed into this repo are both ok).

**Comment by gajus** [comment]
No, such conversion would not be safe.

**Comment by NE-SmallTown** [comment]
Yea, that's what I means. If it is possible, we can convert something needed to `styleName` and preserve some `className` which can't be convert. I know it is hard, but maybe we can cover most cases and tell users to convert some edge cases manually which we can't process.
