### ISSUE TITLE
Display missing styleName anyway?

### ISSUE THREAD

**Issue by morgs32** [gajus/babel-plugin-react-css-modules#135]
This probably belongs on stackoverflow... but maybe this is a feature request

Is there a way to have `handleMissingStyleName` just provide the className anyway? Sort of like `identity-obj-proxy`?

Or is there anyway you can think of to get this functionality? Another babel plugin perhaps?

**Comment by IanVS** [comment]
Interesting.  I'm curious, what is your use case for wanting this behavior?

**Comment by gajus** [comment]
> Interesting. I'm curious, what is your use case for wanting this behavior?

I am guessing to visually mark objects as missing the style name.

**Comment by morgs32** [comment]
I'm letting our customers add their own stylesheets. So I'd like to add
classNames to quite a few dom elements but would love not to have to use a
string for those, and `styles.property` for the rest... Especially in the
extreme case that a component name/ and the CSS file name change...

Anyway I don't use any hashing of the class name so the css sheet provided
by customers persists over time...

Is that a clear example of my use case?

**Comment by IanVS** [comment]
If you know which styles are going to be provided by the customers, could you use `className` for those, and `styleName` for the ones that you're providing?  Or, do you not know ahead-of-time which styles they will be overriding?

**Comment by gajus** [comment]
Sounds like misuse of CSS modules. If customers are expected to provide their own stylesheets, then using `className` for customer classes and `styleName` default classes is an appropriate solution.

If the intent is that the default styles must not be use in case user styles are provided, then you might be better off with completely different solution than CSS modules, e.g. [styled-components](https://github.com/styled-components/styled-components).

**Comment by morgs32** [comment]
Good points all around
