### ISSUE TITLE
Bad object expression created when using anonymous import & runtime resolution

### ISSUE THREAD

**Issue by PCreations** [gajus/babel-plugin-react-css-modules#14]
When using dynamic resolution with anonymous import, the generated object expression by `createObjectExpression.js` does not return a valid AST since the generated property name is prefixed by `random-` and the hypen is not "escaped" by quotes.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/babel-plugin-react-css-modules/pull/12. Thank you @PCreations
