### ISSUE TITLE
filetypes extensions don't support ".module.less"

### ISSUE THREAD

**Issue by wbern** [gajus/babel-plugin-react-css-modules#148]
As title states, it does not seem to be possible to care only about .module-files.

PR #144 seems intended to fix that (include option)

**Comment by wbern** [comment]
Actually, this can already be done using `exclude`.
Saw issue #91 which pointed me in the right direction.

My settings:

```
plugins: [
    (...),
    [
        "react-css-modules",
        {
            context: options.context,
            // include: "\.module\.(less|css)$", // PR pending
            exclude: "^(?!.*module).+\.(less|css)$",
            filetypes: {
                ".less": {
                    syntax: "postcss-less"
                }
            }
        }
    ]
]
```

**Comment by tsnieman** [comment]
For what it's worth, I didn't find ⬆️ this style of exclusion worked for me in my `.babelrc`.

(I authored #144).
