### ISSUE TITLE
Does 5.0 need to be a requirement ?

### ISSUE THREAD

**Issue by solomon23** [gajus/babel-plugin-react-css-modules#15]
Is there a reason for the hard dependency on node v5 ?

**Comment by gajus** [comment]
Where do you see v5 being set as a dependency?

The current package definition says [>5](https://github.com/gajus/babel-plugin-react-css-modules/blob/4ab70fbf9fb0562a62561074a008f76d873eab0d/package.json#L37).

**Comment by solomon23** [comment]
Right, does it need > node 5 ?

**Comment by gajus** [comment]
Are you asking because you are running on Node v4?

There is no guarantee for v4 support.

**Comment by solomon23** [comment]
Yes, we're running 4.6 and this is the first project we've had any trouble installing. I was wondering if it's really using v5 features or it was added for other reasons

**Comment by gajus** [comment]
Sorry, no plan to support v4.
