### ISSUE TITLE
Doesn't work outside of Webpack

### ISSUE THREAD

**Issue by oayres** [gajus/babel-plugin-react-css-modules#153]
This plugin works a treat for me when used inside Webpack. However, I've decided to trial a new module bundler: fuse-box.

Unfortunately, the babel plugin seems to think relative imports like this: `import './Test.scss'` are importing from the root of the project, rather than relative to the file the import is in. It fails to read the scss file.

I've tried forking the repo and manually debugging this, but I've struggled to figure out why it's happening or if there's any way of getting the context of where you are within Babel's plugin handbook. I'm not sure if it's relying on anything from Webpack to function correctly in this regard.

I did however manage to make it work through a very hacky solution (force fuse-box to define babel's `moduleRoot` if not defined and read that from inside this plugin), which isn't really an actual solution.

So... I guess it's a a set of open questions:
a) Has anybody used this outside of Webpack?
b) Contributors, do you rely on anything inside Webpack to resolve files?
c) Does any babel-plugin writers know if it's possible for me to get a files directory path when it's a relative import?

**Comment by gajus** [comment]
> Unfortunately, the babel plugin seems to think relative imports like this

Thats not true. See https://github.com/gajus/babel-plugin-react-css-modules#configuration. Maybe you have misconfigured `context`.

**Comment by oayres** [comment]
@gajus Thanks for the speedy reply! I don't pass in `context` to the plugin. But I've tried a _lot_ of combinations to the option. It doesn't have any impact on the outcome. Any ideas?

**Comment by gajus** [comment]
> I don't pass in context to the plugin.

In most setups you do need to pass the `context` setting. See the examples.

https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js#L4
