### ISSUE TITLE
using  Bem specification is not generated CSS

### ISSUE THREAD

**Issue by ydostyle** [gajus/babel-plugin-react-css-modules#154]
![image](https://user-images.githubusercontent.com/22721444/35546316-c7ceb3d6-05ae-11e8-880f-e75c0474cf95.png)
![image](https://user-images.githubusercontent.com/22721444/35546323-ce63350a-05ae-11e8-8ec2-59724fd0af42.png)
![image](https://user-images.githubusercontent.com/22721444/35546336-e01dfc4e-05ae-11e8-820f-db3a54c0440b.png)

**Comment by gajus** [comment]
I suggest start by inspecting that the generated CSS is what you expect it to be.

Based just on this picture, I don't see a reason why this shouldn't work.

**Comment by hinok** [comment]
@gajus I've found that sometimes to make it work I need to clear `babel-loader` in `.cache`, I mean `my-project/node_modules/.cache/babel-loader`.

I'm not sure where is the problem, in `babel-loader` or `babel-plugin-react-css-modules`.
This can be easily replicated in my case when I write first `styleName` for a class that doesn't exist yet:

**`MyComponent.js`**
```
import from './MyComponent.scss';
// ...
<div styleName="product-box"></div>
```

Then save **`MyComponent.js`** file, after that I create this class in **`MyComponent.scss`**, then save **`MyComponent.scss`** and for 99% this class won't be used and the only workaround is to purge `.cache/babel-loader`.

**Comment by mikeyshing88** [comment]
Does anybody have further information regarding this by any chance?

**Comment by gajus** [comment]
@hinok Try disabling `cacheDirectory` setting https://github.com/gajus/babel-plugin-react-css-modules/issues/160.
