### ISSUE TITLE
Feature Request: Help out with Critical CSS

### ISSUE THREAD

**Issue by gja** [gajus/babel-plugin-react-css-modules#157]
Proposal:
When a React Component tree is rendered, it should be possible to record which css rules were actually used. 

This is done by other libraries (such as `isomorphic-style-loader`) using a Higher Order Component, which uses context to pass around a callback which is called with styles that are loaded.

My proposal is as follows. If opts.contextCallback is set, then call the callback before render. This could be used as follows. (say opts.contextCallback is set to 'insertCss') (snippet influenced by `isomorphic-style-loader`)

```javascript
const css = new Set();
const context = { insertCss: (styles) => styles.forEach(style => css.add(style); };
const body = React.renderToString(<WithContext context={context}/><MyPage></WithContext>)
const cssText = [...css].join("");
```

At the beginning of every render, this would do something like the following:
```javascript
if(context.insertCss)
  context.insertCss(styles)
```

Let me know thoughts on this. Alternatively, this could be created as a separate babel plugin.

**Comment by gajus** [comment]
Whats the use case?

**Comment by gja** [comment]
Sorry I was unclear. This feature would be used to extract the css that is actually required for a page, so that the server can add a style tag with the css inline. It's basically critical CSS, but for the entire page, not just above the fold.

Consider you have components C1,C2,C3...C10, each which has css style .c1 { }, .c2 {}...

If I my homepage looks like

```html
<div>
  <C1>
  <C2>
  <C3>
</div>```

then I would like to extract a CSS which only contains the 3 css rules required for C1 to C3, without the bloat of CSS from C4 to C10. Naturally, this is only relevant for server side render.

Currently, this is achieved by loaders like `isomorphic-style-loader` by creating a higher order component, which triggers a callback when a component is rendered, with the styles it uses. However, this feels like a pain, as I have to wrap every single component that has styles

**Comment by gajus** [comment]
@gja "critical CSS" (CSS used to load the page) will depend on multiple criteria (such as media queries) that cannot be computed accurately at a build time, i.e. you can only compute them at a run time.
