### ISSUE TITLE
Not transforming styleName to className.

### ISSUE THREAD

**Issue by hbowden** [gajus/babel-plugin-react-css-modules#159]
I'm trying to convert a project from react-css-modules to the babel-plugin. However the styleName prop is not being transformed so the css styles are not being applied.  I get the warning below in my console as a result.

![screen shot 2018-02-15 at 10 18 48 pm](https://user-images.githubusercontent.com/12447474/36293345-4e0c1b36-129e-11e8-84e5-9213fdbb064f.png)

Also here is a screenshot showing the rendered HTML in the browser. Note that styleName is being passed to the DOM and not class.

![screen shot 2018-02-15 at 10 20 24 pm](https://user-images.githubusercontent.com/12447474/36293366-89ff06c6-129e-11e8-8a25-6dff58f89141.png)

To reproduce you can follow the steps below.

```
git clone https://github.com/DigitalRiver/react-atlas

cd react-atlas

git checkout compose

npm install

npm run docs:dev
```
Now visit http://localhost:6060/#accordion

The webpack config and babelrc files can be found inside the react-atlas repo in the compose branch. Let me know if you need more information. 

Thanks Harrison.

**Comment by hbowden** [comment]
The component in question is located at `react-atlas/components/Accordion` or at https://github.com/DigitalRiver/react-atlas/tree/compose/components/Accordion

**Comment by yume-chan** [comment]
I see you are using `styleguide.config.js` to override `webpackConfig`, and the babel config in your `styleguide.config.js` doesn't contain a `plugins: ['react-css-modules']` config, so this plugin doesn't run when you use `styleguidist server` to run your project.

I added that line to your `styleguide.config.js` and it throws two errors:

```` text
 FAIL  Failed to compile

./components/Alert/Alert.js
Module build failed: Error: react-atlas/components/Alert/Alert.js: Cannot use styleName attribute without importing at least one stylesheet.
    at Array.map (<anonymous>)
./components/Dropdown/Dropdown.js
Module build failed: Error: react-atlas/components/Dropdown/Dropdown.js: Cannot use styleName attribute without importing at least one stylesheet.
    at Array.map (<anonymous>)
````

**Comment by hbowden** [comment]
@yume-chan Thank you for pointing out that the config is in `styleguide.config.js` we can close this.
