### ISSUE TITLE
How to test for styles in Mocha+Enzyme+Chai

### ISSUE THREAD

**Issue by pkuczynski** [gajus/babel-plugin-react-css-modules#168]
How can I test for elements receiving correct style? Here is my current setup

```js
// component.js
import React from 'react'
import './component.scss'
 
const Component = () => (<div styleName="abc">...</div>)
```

```css
/* component.scss */
.abc {
  color: red;
}
```

```js
// component.test.js
import React from 'react'
import Component from './component'

describe('Component', () => {
  it('Should work...', () => {
    const wrapper = shallow(<Component/>)
    expect(wrapper).to.have.prop('styleName', '.abc')  // <--- this fails
  })
})
```

Styles render correctly in the app, but I am finding trouble to test against them in my tests. Any help will be highly appreciated...

**Comment by gajus** [comment]
I am guessing that your test cases are being processed using babel transpilers. That means that you need to look at whatever is the transpiled code and write conditions to match that. Transpiled code does not have `styleName` property – it will be replaced by `className`.

**Comment by pkuczynski** [comment]
That's the problem. How can I discover the class name after transpilation? Seems it does not work whatever I tried...

**Comment by mildrenben** [comment]
@pkuczynski did you ever figure this out? I'm having the same problem

**Comment by pkuczynski** [comment]
As we are using the latest version of Babel (still in beta) our configs are in javascript and then you can do:

```
    [
      'react-css-modules',
      {
        generateScopedName: process.env.NODE_ENV === 'test' ? '[local]' : '[name]__[local]__[hash:base64:6]'
        }
      }
    ],
```
