### ISSUE TITLE
file not set up for runtime resolution if runtime resolution is needed in more than one file

### ISSUE THREAD

**Issue by PCreations** [gajus/babel-plugin-react-css-modules#17]
This is because the following vars are not scoped by file, but to the current build :

*[index.js (L19-21)](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/index.js#L19-L21)*
```js
  let styleModuleImportMap;
  let importedHelperIndentifier;
  let styleModuleImportMapIdentifier;
```

It works for the first file that need runtime resolution but when a second file need runtime resolution, the following condition skips the process :

*[index.js (L105)](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/index.js#L105)*
```js
if (!importedHelperIndentifier)
```

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/babel-plugin-react-css-modules/pull/12. Thank you @PCreations
