### ISSUE TITLE
Please ignore imports that start with things like '!!raw!'

### ISSUE THREAD

**Issue by jjinux** [gajus/babel-plugin-react-css-modules#170]
I have some code that pulls in an import like:

```
import icomoonCss from '!!raw!base-components/universal/icomoon/icomoon.global.less';
```

It's working with the .less source code dynamically. The current ways that you can configure the project to skip files (i.e. exclude) don't work because they happen after the file has already been resolved. It doesn't work with something that starts with '!!raw!'. I'm not sure how common this is, but it'd be nice to just ignore imports like that.

**Comment by jjinux** [comment]
In src/index.js, it says:

```
if (stats.opts.exclude && getTargetResourcePath(path, stats).match(new RegExp(stats.opts.exclude))) {
```

getTargetResourcePath assumes you can resolve the path. That doesn't work for '!!raw!'.

I suspect it also doesn't work very well if you're making use multiple roots by having multiple things in Webpack's resolve.modules list, but that's a separate issue ;)

**Comment by gajus** [comment]
I don't fully comprehend the use case, but I can see there being a use case for wanting to exclude certain styles from being included.

Refer to the `exclude` configuration.

**Comment by jjinux** [comment]
This problem happened to me again today. I was importing a less file via `import themeVariables from '!less-vars!./variables.global.less';`. That way, I could use the less styles via JavaScript. I think it just should ignore imports that start with '!'.

**Comment by jjinux** [comment]
And, btw, exclude doesn't work. See my description at the top.

**Comment by jjinux** [comment]
I think it should just ignore all imports that start with ! because it's a sign that a Webpack loader is going to do some additional processing.

**Comment by jjinux** [comment]
Please see: https://github.com/gajus/babel-plugin-react-css-modules/pull/178
