### ISSUE TITLE
Please output more debugging information for "CSS module does not exist"

### ISSUE THREAD

**Issue by jjinux** [gajus/babel-plugin-react-css-modules#171]
In getClassName.js, there are exceptions such as `console.warn('CSS module does not exist.');`. That error is really hard to debug because it doesn't give much context. If you included importName and moduleName in the exception, it'd be a lot easier to debug. I've resorted to adding console.log statements in order to workaround this in the meantime.

Here's a sample error message I get via Karma:

```
Chrome 63.0.3239 (Mac OS X 10.13.3) ERROR
  Uncaught Error: Module build failed: Error: /Users/jjbehrens/Code/udemy-django/static/src/udemy/js/organization-common/expired-modal/expired-modal-content/expired-trial.react-component.js: CSS module does not exist.
    at getClassNameForNamespacedStyleName (/Users/jjbehrens/Code/udemy-django/static/node_modules/babel-plugin-react-css-modules/dist/getClassName.js:47:13)
    at styleNameValue.split.filter.map.styleName (/Users/jjbehrens/Code/udemy-django/static/node_modules/babel-plugin-react-css-modules/dist/getClassName.js:68:14)
...
```

**Comment by gajus** [comment]
PR welcome.

**Comment by jjinux** [comment]
See: https://github.com/gajus/babel-plugin-react-css-modules/pull/179/files

**Comment by jjinux** [comment]
This has been resolved.
