### ISSUE TITLE
Feature Request: Add an option to specify the module path of getClassName

### ISSUE THREAD

**Issue by otakustay** [gajus/babel-plugin-react-css-modules#172]
Currently `babel-plugin-react-css-modules` requires to be installed as runtime dependency since it generates an import to `babel-plugin-react-css-modules/dist/browser/getClassName`

In our case, we use a private package to encapsulate all babel plugins, we don't want our users to be aware to the `babel-plugin-react-css-modules`, neither do we want them to install it themselves

We think a solution could be this plugin providing an option `runtimeModulePath` to identify this runtime helper module, for example when our private package is `our-fe-tools`, we config it as:

```javascript
[
  require.resolve('react-css-modules'),
  {
    runtimeModulePath: 'our-fe-tools/lib/styleNameHelper'
  }
]
```

Then import statement is transformed to `import getClassName from 'our-fe-tools/lib/styleNameHelper'` so we can entirely encapsulate all babel plugins

**Comment by gajus** [comment]
This seems entirely esoteric issue with no practical applications.

**Comment by jpsear** [comment]
This would be a great feature. @gajus For a use-case,  think of `create-react-app`, where all the webpack and build configuration is abstracted away from the consumer... 

@otakustay Did you find a way around this? What you explained is _exactly_ what we are trying to do too...l
