### ISSUE TITLE
Publish current master to npm

### ISSUE THREAD

**Issue by gbiryukov** [gajus/babel-plugin-react-css-modules#177]
It has new features that nice to have

**Comment by gajus** [comment]
How to migrate from react-css-modules to babel-plugin-react-css-modules?

**Comment by gbiryukov** [comment]
@gajus looks like this integration is broken 
https://travis-ci.org/gajus/babel-plugin-react-css-modules/jobs/367242582#L1248

it requires node `8` in order to work but [travis.yml](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/.travis.yml#L3) contain only `7`

**Comment by gajus** [comment]
Fixed.

**Comment by gbiryukov** [comment]
thanks a lot 👍
