### ISSUE TITLE
No className generated when styleName is resolved at runtime

### ISSUE THREAD

**Issue by PCreations** [gajus/babel-plugin-react-css-modules#18]
When using runtime resolution to find the actual `styleName`, no `className` attribute is added to the component, making it unstyled.

**Comment by gajus** [comment]
@PCreations Is still still an active issue?

**Comment by PCreations** [comment]
@gajus Yes it is, do you understand it or do you want me to rephrase it ?

**Comment by PCreations** [comment]
@gajus I'm actually trying to solve this one, PR should come today.

**Comment by PCreations** [comment]
@gajus Should be fixed by #19

**Comment by gajus** [comment]
Thank you!

p.s. I saw your email. To follow up is on my list of things to do.
