### ISSUE TITLE
Use original className in console when using css modules

### ISSUE THREAD

**Issue by Igor-Vuk** [gajus/babel-plugin-react-css-modules#182]
I am using babel-plugin-react-css-modules. This is my configuration isnide of webpack.

```
  devtool: 'source-map',
      {
        test: /\.local\.(css|scss)$/,
        use: [
          'style-loader',
          'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
          'postcss-loader?sourceMap',
          'sass-loader?sourceMap',
          {
            loader: 'sass-resources-loader?sourceMap',
            options: {
              resources: [ path.resolve(__dirname, './src/client/styling/styles/variables.scss'), ],
            },
          },
        ],
      },
```

Inside of my component when I add something like this

`<h2 styleName="feature-one">Feature Scene</h2>`

And inside my css file I add this

```
.feature-one {
   color: red;
 }
```

Everything works regarding the styles but if I inspect the element in chrome console this is what I see

```
.scenes-routeComponents-feature-components-___formComponent-local__container___18_A8 .scenes-routeComponents-feature-components-___formComponent-local__feature-one___1Hp46 {
  color: red;
}
```

It is the generated css module name. Can I somehow map this and show the original class name 'feature-one' when inspecting the element?

**Comment by danawoodman** [comment]
Isn't the whole point of this project not to do that? It is supposed to create namespaced styles for components, so this seems exactly what it is supposed to be doing.

**Comment by gajus** [comment]
> Isn't the whole point of this project not to do that? It is supposed to create namespaced styles for components, so this seems exactly what it is supposed to be doing.

I think @Igor-Vuk is asking this for debugging purposes, e.g. `data-original-class-name="feature-one"`.

**Comment by gajus** [comment]
@Igor-Vuk In general, this shouldn't be needed though. You can use variable to link module name to the original class name, which you are already doing using `[path]___[name]__[local]___[hash:base64:5]`.

**Comment by Igor-Vuk** [comment]
@gajus yes, I am asking for debugging purpose. It's really hard to debugby using `[path]___[name]__[local]___[hash:base64:5]` this and inspecting elements in console. You can not see tree from the forest. I can for example use just this `[local]` and get just the class name in console but whats the purpose then in using css modules.
I am sorry, I don't see a solution in your answer, can you explain how do I get clean output while inspecting and debugging?
