### ISSUE TITLE
How to pass custom stylename prop to React component

### ISSUE THREAD

**Issue by lolbeans** [gajus/babel-plugin-react-css-modules#190]
Hi, say I have the following:

```jsx
import React from 'react';
import './button.css';

const Button = ({ children, ...rest }) => (
  <button {...rest} styleName="btn">{children}</button>
);
```

And I use it in another component:

```jsx
// foo.js
import Button from './button';
import './foo.css';

const Foo = () => <div><Button>text</Button>;
```

Is there an easy way to pass a custom style name from foo.css that do both:

1. Override the .btn stylename or
2. Append an extra class name

I've tried ```<Button styleName="xx">text</Button>``` but it doesn't seem to work. I've also tried using the attributeNames option to map a custom prop extraStyleName to extraClassName, but this means having to do the following which is not ideal:

```jsx
const Button = ({ children, extraClassName, ...rest }) => (
  <button {...rest} styleName="btn" className={extraClassName}>{children}</button>
);
```

Thanks

**Comment by gajus** [comment]
Not with using `babel-plugin-react-css-modules`.

You can just use the `css-modules` and pass the style reference.

```js
import Button from './button';
import styles as './foo.css';

const Foo = () => <div><Button myOverrideStyle={styles.myButton}>text</Button>;

```

**Comment by viralganatratb** [comment]
Ah okay - thanks

**Comment by ilovebeatles** [comment]
Same problem here, it would be really helpful to create something like this https://github.com/gajus/react-css-modules#loops-and-child-components
