### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by cooksworld** [gajus/babel-plugin-react-css-modules#191]
Trying to install using `npm install babel-plugin-react-css-modules --save` - getting the following: 

`npm http GET https://registry.npmjs.org/babel-plugin-react-css-modules
npm ERR! TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
npm ERR!     at new ClientRequest (_http_client.js:105:13)
npm ERR!     at TunnelingAgent.request (https.js:272:10)
npm ERR!     at TunnelingAgent.createSocket (/usr/local/lib/node_modules/npm/node_modules/request/tunnel.js:116:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/local/lib/node_modules/npm/node_modules/request/tunnel.js:188:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/local/lib/node_modules/npm/node_modules/request/tunnel.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:239:16)
npm ERR!     at Object.request (https.js:272:10)
npm ERR!     at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/main.js:510:30)
npm ERR!     at Request.end (/usr/local/lib/node_modules/npm/node_modules/request/main.js:915:28)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/request/main.js:375:12
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 17.7.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "babel-plugin-react-css-modules" "--save"
npm ERR! cwd /Users/xyz/Sites/xyz
npm ERR! node -v v10.6.0
npm ERR! npm -v 1.1.65
npm ERR! code ERR_UNESCAPED_CHARACTERS`

**Comment by gajus** [comment]
Looks like NPM issue. Contact NPM support.
