### ISSUE TITLE
undefined class if both className and styleName are JSX expressions

### ISSUE THREAD

**Issue by gewfy** [gajus/babel-plugin-react-css-modules#20]
Hi!
I want the parent component to be able to set classes on it's child components. Therefore I need the `className` to be appended at runtime. But this:

```JSX
<div className={this.props.className} styleName={"foo"}>
```

Renders:

```HTML
<div class="undefined foo___1ZSNk">
```

Even if the parent component passes className to the child component.

Thank you!

**Comment by gajus** [comment]
Fixed. Thank you for reporting.
