### ISSUE TITLE
version 3.4.3 breaks packing when used with babel-core 6.x

### ISSUE THREAD

**Issue by yuvke** [gajus/babel-plugin-react-css-modules#213]
It seems that form version 3.4.3 `babel-plugin-react-css-modules` requires babel 7.
If this was the intent, then this is a breaking change and should be communicated via a major release, not a patch.

specifically, this is the relevant part of the config I'm using:
``` javascript
const contextDir = path.resolve(__dirname, 'src');
const webpackConfig = {
    module: {
        rules: [{
           test: /\.jsx?$/,
           include: path.resolve(__dirname,'..'),
           use: [{
                loader: 'babel-loader',
                options: {

                    presets: ['react'],
                    plugins: [
                        [
                            'babel-plugin-react-css-modules',
                            {
                                context: contextDir,
                                filetypes: {
                                    ".scss": {
                                        "syntax": "postcss-scss"
                                    }
                                },
                                generateScopedName: '[name]__[local]___[hash:base64:5]'
                            }
                        ],
                        "transform-object-rest-spread"
                    ]
                }
            }],
            exclude: /node_modules/
       }]
}
```

**Comment by LeonDWong** [comment]
Same problem here, could anyone help?

**Comment by OpherV** [comment]
@LeonDWong Try to explicitly lock the package to version 3.4.2 in your package.json

![image](https://user-images.githubusercontent.com/3951311/48772185-43d02c80-eccc-11e8-9dce-84613bbb2ec8.png)

**Comment by sthzg** [comment]
> If this was the intent, then this is a breaking change and should be communicated via a major release, not a patch.

Sorry for causing these problems with yesterday's PRs. A few of the last builds were failing and I was meaning to provide a PR to make the builds green again. 

I agree with @yuvke's statement above. Pinning the dependency to `3.4.2` as suggested by @OpherV should work.

@gajus Do you think it makes sense to push the babel 7 upgrade to a 4.x. version line or some kind of `@next` release tag?

**Comment by gajus** [comment]
That would have been a good choice. I would advice to simply pin the dependency at this point.

Happy to unpublish the latest release and release as v4, though.

👍 , ping me if you suggest this action.

**Comment by JZBo** [comment]
> If this was the intent, then this is a breaking change and should be communicated via a major release, not a patch.

> That would have been a good choice. I would advice to simply pin the dependency at this point.
> Happy to unpublish the latest release and release as v4, though.

I would really welcome and be thankful for that choice, if it were possible. Having a patch release which results in a breaking change causes a lot of problems for us users.

Thanks for your availability.

**Comment by gajus** [comment]
* v3.4.3, v3.4.4 have unpublished.
* v4.0.0 has been published.
