### ISSUE TITLE
Create option to generate className even if style is missing

### ISSUE THREAD

**Issue by antonholmquist** [gajus/babel-plugin-react-css-modules#217]
This is a use case I have that creates problem with webpack dev middleware:

1. Add style to a React element that doesn't yet have a corresponding class in the css file
2. Add the class to the css file
3. Webpack would need to reload the js file to resolve again, so I need to go to the js file and re-save it to trigger the reload.

This could probably be fixed with an option to generate classNames even though no corresponding class yet exist.

What's your view on this? I can see this would be useful during development and with certain setups.

Would also like to add that I'm very happy with this plugin! Thank you so much for putting it together.

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/135
