### ISSUE TITLE
`composes .. from ...` statements no longer work

### ISSUE THREAD

**Issue by ewohlken** [gajus/babel-plugin-react-css-modules#22]
If I have a class A in index.css that composes a class B from test.css, the component that has attribute `styleName='A'`should inherit both the A class styles and the B class styles. However this is not the case, see my example below:

https://github.com/ewohlken/babel-plugin-react-css-modules-test/

**Comment by ksrb** [comment]
@ewohlken try replacing:
`css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]`

with:
`css?modules&importLoaders=2&localIdentName=[path]___[name]__[local]___[hash:base64:5]`

**Comment by gajus** [comment]
Thank you @ksrb
