### ISSUE TITLE
Included demo doesn't seem to work

### ISSUE THREAD

**Issue by FullStackForger** [gajus/babel-plugin-react-css-modules#223]

**Comment by gajus** [comment]
PR welcome.

**Comment by matigda** [comment]
that's a great attitude!
I'm trying to use this plugin, it's not working. I'm looking at the demo - not working. Going through issues and what I see? "Hey, it's not working, but PR is welcome".
Most discouraging thing ever.

**Comment by hinok** [comment]
@FullStackForger I checked it seems that it's working correctly. Could you describe your problem?

<img width="560" alt="zrzut ekranu 2019-02-8 o 01 52 19" src="https://user-images.githubusercontent.com/1313605/52452701-73ad0480-2b44-11e9-82e4-963d27976974.png">

<img width="703" alt="zrzut ekranu 2019-02-8 o 01 53 55" src="https://user-images.githubusercontent.com/1313605/52452706-77408b80-2b44-11e9-8c9b-13c2dfa64416.png">
