### ISSUE TITLE
Bug in build-helper

### ISSUE THREAD

**Issue by alvteren** [gajus/babel-plugin-react-css-modules#232]
Hi, sorry for my English

In version since 5.0.0, I have a problem with building my app
![joxi_screenshot_1550750991796](https://user-images.githubusercontent.com/17045072/53168040-c5489b00-35ea-11e9-8f86-5c7ab3694a2a.png)

When I watched file `/dist/browser/getClassName.js`. It contains code in line 8 `var _optionsDefaults = _interopRequireDefault(require("./schemas/optionsDefaults"));`

I think it has to contain  `../schemas/optionsDefaults` instead of `./schemas/optionsDefaults`

I hope that I wrote clear and you can understand me.

**Comment by gajus** [comment]
@AlbertLucianto can you have a look at this one? Seems related to the recent changes.

**Comment by alvteren** [comment]
I think It related to changes on script "build-helper" in package.json

**Comment by fazo96** [comment]
Running into this as well. Using `4.0.0` the bug does not happen

**Comment by AlbertLucianto** [comment]
@gajus sure. @alvteren you're right, it seems there's problem in the relative path on the build-helper. I'll look into this.

**Comment by alvteren** [comment]
Thank you for fast reaction
