### ISSUE TITLE
I don't know It doesn't work

### ISSUE THREAD

**Issue by XOneto9** [gajus/babel-plugin-react-css-modules#236]
I'm not sure how to it work?

I have old version react-app with react-css-module not babel-plugin-react-css-modules.
For the problem of SSR, but, I should change module of style (not using high order component), so I find this plugin.

but, I don't know I just change .babelrc but not match sass.

As test I use
1. create-react-app v2.1.5 at latest version
2. using .scss file (it is made using basic sample from cra by me)
 just it not something big!

```
"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "react-css-modules",
        {
          "generateScopedName": "[name]__[local]___[hash:base64:5]",
          "filetypes": {
            ".scss": {
              "syntax": "postcss-scss"
            }
          }
        }
      ]
    ]
  },
```

and Webpack configuration is not changed
just create-react-app eject. 

the results is ..

<img width="341" alt="2019-02-25 1 26 46" src="https://user-images.githubusercontent.com/18350072/53301976-92c5c900-389c-11e9-805b-bac7c22c01ca.png">
<img width="450" alt="2019-02-25 1 26 34" src="https://user-images.githubusercontent.com/18350072/53301978-935e5f80-389c-11e9-8439-a7055ab27c8a.png">
<img width="530" alt="2019-02-25 1 26 31" src="https://user-images.githubusercontent.com/18350072/53301979-935e5f80-389c-11e9-98ec-f22fa3631609.png">

In the html, the styleName is changed, but not matching with sass file.

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/218

**Comment by XOneto9** [comment]
@gajus Hi,
I look around #218 also #83 for me taged issue.
but until I'm not sure, because I have already set configuration like demo on the create-react-app v2.1.5

also , I set the configuration like next,,
```
const context = path.resolve(__dirname, 'src');

module : {
    rules: [
/********some code *****/
        {
            oneOf:[
                {
                  test: /\.js$/,
                  include: path.resolve(__dirname, './src'),
                  loader: 'babel-loader',
                  query: {
                      plugins: [
                          '@babel/transform-react-jsx',
                      ['react-css-modules', {
                          context
                      }]
                    ]
                  },
                },
            ]
        }

/******some code******/
```

but I can not see css file changed hash name.
<img width="1280" alt="2019-02-25 6 41 19" src="https://user-images.githubusercontent.com/18350072/53328291-f992c300-392c-11e9-9976-0e468c9a2450.png">
