### ISSUE TITLE
how to work on create-react-app v2?

### ISSUE THREAD

**Issue by XOneto9** [gajus/babel-plugin-react-css-modules#237]
hi, a few days ago, I post some question about that how to it work because of getting error.
So, I try to some attempt about to work, but the problem is that if I set the context, configuration of Webpack and etc... the create-react-app v2 has changed to making hashed style name.

In create-react-app v2, the style module format is add "module" character like as 
```
import s from './App.module.scss'
```
but this babel-plugin-react-css-modules of hashed name in the babelrc is like as
`        "generateScopedName": "[name]_[local]__[hash:base64:5]",
`
so, the results of product class name is like that
```
<div class="App-module_App__3RxO-">
```
including "App-module" as [name] .

so I don't know how to use in the create-react-app v2
if I exclude character of name "module" in the scss name, then the create-react-app has not recognized.
how can I do that...??

**Comment by AlbertLucianto** [comment]
@XOneto9 I think one workaround is to change the webpack config from the ejected app

```diff
{
  test: cssModuleRegex,
  use: getStyleLoaders({
    importLoaders: 1,
    sourceMap: isEnvProduction
      ? shouldUseSourceMap
      : isEnvDevelopment,
    modules: true,
-   getLocalIdent: getCSSModuleLocalIdent,
+   localIdentName: '[name]__[local]___[hash:base64:5]',
  }),
},
```

**Comment by XOneto9** [comment]
@AlbertLucianto 
Hi, Thanks to reply.
yes, nothing to way to resolve this problem is your solutions.

thanks.

**Comment by gajus** [comment]
See:

* https://github.com/facebook/create-react-app/issues/5113
* https://github.com/sharegate/craco/blob/master/recipes/use-babel-plugin-react-css-modules/craco.config.js

**Comment by jackwatson86** [comment]
Hello,

I've tried the above craco configuration together with the default babel-plugin-react-css-modules installation `npm install babel-plugin-react-css-modules --save` but importing with `import styles from './styles.css' and referencing to it with `styleName='my-style'` doesn't work for me.

Am I missing something?
