### ISSUE TITLE
Can I configure it in babel.config.js?

### ISSUE THREAD

**Issue by linxiangjun** [gajus/babel-plugin-react-css-modules#238]
I have been plagued by this problem for a long time, I configured webpack.dev.conf.js and babel.config.js, but the <style> style directly applies the hash name of css-module, and when I configure styleName, they Can't match. The following is my configuration
webpack.dev.conf.js:
`
      {
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]-[local]-[hash:base64:5]',
            },
          },
          { loader: 'less-loader' },
        ]
      }
`
babel.config.js:
`
[
        'babel-plugin-react-css-modules',
        {
          'generateScopedName': '[name]-[local]-[hash:base64:5]',
          'exclude': 'node_modules',
          'context': path.resolve(__dirname, 'src'),
          'webpackHotModuleReloading': true,
          'filetypes': {
            '.less': {
              'syntax': 'postcss-less'
            }
          }
        }
      ]
`

My webpack config in 'webpack' folder under the root directory,and babel.config.js in root directory

**Comment by AlbertLucianto** [comment]
@linxiangjun can you provide an example output of your case?

**Comment by linxiangjun** [comment]
**babel.config.js:**
![1551338941 1](https://user-images.githubusercontent.com/20981110/53548987-018d7580-3b6e-11e9-8b4b-04c279e22801.jpg)
**webpack.dev.conf.js:**
![1551338963 1](https://user-images.githubusercontent.com/20981110/53548990-03573900-3b6e-11e9-83d6-b431a4d4a6fa.jpg)
**project directory**
![1551339056 1](https://user-images.githubusercontent.com/20981110/53548993-06522980-3b6e-11e9-827c-02687aaf03e7.jpg)

**Comment by linxiangjun** [comment]
> @linxiangjun can you provide an example output of your case?

All styles are automatically converted to hash names(This should not be like this)，when i use 'styleName' on tag，This can be converted to hash names,But they are not match

**style**
![1551339190 1](https://user-images.githubusercontent.com/20981110/53549219-9f814000-3b6e-11e9-88e6-876fdaff708d.jpg)
**set styleName**
![1551339208 1](https://user-images.githubusercontent.com/20981110/53549263-bb84e180-3b6e-11e9-8ed0-aa835f7692fa.jpg)

**Comment by AlbertLucianto** [comment]
@linxiangjun I think you should make sure the `context` option is the same with `context` in webpack config.

And if you do not set the `context` in webpack config, based on webpack documentation:

> By default the current directory is used, but it's recommended to pass a value in your configuration. This makes your configuration independent from CWD (current working directory).

Anyway, on the screenshot your `webpack.dev.conf.js` is in build folder, but you said

> My webpack config in 'webpack' folder under the root directory,and babel.config.js in root directory

**Comment by linxiangjun** [comment]
> @linxiangjun I think you should make sure the `context` option is the same with `context` in webpack config.
> 
> And if you do not set the `context` in webpack config, based on webpack documentation:
> 
> > By default the current directory is used, but it's recommended to pass a value in your configuration. This makes your configuration independent from CWD (current working directory).
> 
> Anyway, on the screenshot your `webpack.dev.conf.js` is in build folder, but you said
> 
> > My webpack config in 'webpack' folder under the root directory,and babel.config.js in root directory

Thx,I said the wrong file name,I will go to configure the webpack context and try again.
