### ISSUE TITLE
styleName not working when className === component name?

### ISSUE THREAD

**Issue by iblq** [gajus/babel-plugin-react-css-modules#251]
code like this:
```js
const Home = () => {
    return <div styleName="home">home</div>;
};
```
any one have same problem?

**Comment by gajus** [comment]
Define not working?

What is the generated `className`.

Closing this until further details provided.

**Comment by iblq** [comment]
o, sorry, detail:     like my code, when the styleName is 'home' or 'Home',   the component's name is 'Home' also,  style not work 
![120F5B50FB4B7A7FE2AAF3533A4E2F74](https://user-images.githubusercontent.com/22744924/57357679-1279e900-71a6-11e9-9ca4-96015d226fe4.png)

**Comment by gajus** [comment]
What is this rendered to?

The way to debug it is to check what is the resulting `className` when the page is loaded and if that class name is exported by the CSS module.

**Comment by iblq** [comment]
> What is this rendered to?
> 
> The way to debug it is to check what is the resulting `className` when the page is loaded and if that class name is exported by the CSS module.

emmmm... that's strang,  my mate and me get this bug this morning, but now it's work well,  maybe some webpack config or package version has problem. thx for your reply
