### ISSUE TITLE
Webpack alias option

### ISSUE THREAD

**Issue by SorEduard** [gajus/babel-plugin-react-css-modules#254]
I saw some issues about wepback alias option (e.g. #25, #46, #118), then i've maded this feature with few lines. 
Usage with new option in babel configuration, like:
```json
"plugins": [
  ["react-css-modules", {
    "webpackConfig": "/path/to/webpack.config.js" 
  }]
]
```

Can I PR this?

**Comment by gajus** [comment]
There are already lower level workarounds, e.g.

https://github.com/gajus/babel-plugin-react-css-modules/issues/46#issuecomment-414130223

No plan to support this.
