### ISSUE TITLE
After migrating from react-css-module to babel-plugin-react-css-modules: react-datePicker styling does not work. 

### ISSUE THREAD

**Issue by Bhushankumar-pawar** [gajus/babel-plugin-react-css-modules#260]
Migrated our project from react-CSS-module to babel-plugin-react-CSS-modules: react-datePicker styling does not work as expected. 

expected Behaviour: 
<img width="302" alt="datePickerExpected" src="https://user-images.githubusercontent.com/23053040/60315949-527b7200-9986-11e9-8027-3354f3e6fe97.png">

But we got the result without styling:
<img width="744" alt="datePickerIssue" src="https://user-images.githubusercontent.com/23053040/60315977-6cb55000-9986-11e9-9ce7-4a18ffcb379c.png">

Webpack config.Js

```
 {
      test: /\.css$/,
      use: [{ 
        loader: "style-loader"
      },{
        loader: miniCssExtractPlugin.loader,
        options: {
          sourceMap: true,
          publicPath: "../"
        }
      }, {
        loader: "css-loader",
        options: {
          importLoaders: 1,
          modules: true,
          localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
          context
        }
      }, {
        loader: "postcss-loader"
      }],
    }
```

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/259
