### ISSUE TITLE
styleName becomes stylename (lowercase)

### ISSUE THREAD

**Issue by ZhouYuTao2017** [gajus/babel-plugin-react-css-modules#277]
jsx
<img width="1161" alt="屏幕快照 2019-11-15 12 05 14" src="https://user-images.githubusercontent.com/30223113/68916290-4448b980-07a0-11ea-9efb-665e1aa5f095.png">

webpack css-loader
<img width="946" alt="屏幕快照 2019-11-15 12 06 44" src="https://user-images.githubusercontent.com/30223113/68916347-7bb76600-07a0-11ea-8e61-ab200029064e.png">

my .babelrc
![image](https://user-images.githubusercontent.com/30223113/68916396-be793e00-07a0-11ea-8055-a76848cef6c0.png)

actual
![image](https://user-images.githubusercontent.com/30223113/68916439-eb2d5580-07a0-11ea-874e-4757a9854aa8.png)

**Comment by gajus** [comment]
This looks like some sort of misconfiguration webpack/ babel. There is no logic in our codebase that would lowercase props.

**Comment by ZhouYuTao2017** [comment]
> This looks like some sort of misconfiguration webpack/ babel. There is no logic in our codebase that would lowercase props.

thanks,I'll check it out . babelrc

**Comment by minicopper** [comment]
> > This looks like some sort of misconfiguration webpack/ babel. There is no logic in our codebase that would lowercase props.
> 
> thanks,I'll check it out . babelrc

may i know which configuration is error？i am boring with the same error

**Comment by Neighborwan** [comment]
I get this error too. can some one tell me how to fix it?
