### ISSUE TITLE
Redundant mapping object in production output

### ISSUE THREAD

**Issue by pot-code** [gajus/babel-plugin-react-css-modules#278]
Happened to get two class name mapping objects in production code

first:
![image](https://user-images.githubusercontent.com/17687881/69148348-0edcfc80-0b0f-11ea-97dd-42e34586d54f.png)

second:
![image](https://user-images.githubusercontent.com/17687881/69148362-156b7400-0b0f-11ea-94da-210d11f83db5.png)

react code:
![image](https://user-images.githubusercontent.com/17687881/69148378-1ef4dc00-0b0f-11ea-9a5d-c3951d571892.png)

The component has already used the **mapped** className, there is no need to emit the mapping object in final build if I understand it correctly.

**Comment by gajus** [comment]
A patch is welcome.

**Comment by pot-code** [comment]
haven't used it for a while, just close it
