### ISSUE TITLE
Typescript Babel HOW TO.

### ISSUE THREAD

**Issue by diegolaciar** [gajus/babel-plugin-react-css-modules#31]
Hi!

I cant get this working with babel+typescript.
Anyone knows a basic example project on the web with Typescript AND babel-plugin-react-css-modules? 

In order to use Typescript React and the plugin, a d.ts file will be need for use 'styleName ' attribute?

How can I import css modules with typescript ?

I also posted related, similar issue here: http://stackoverflow.com/questions/41336858/how-to-css-modules-with-typescript-react-and-webpack

Thanks,

**Comment by mjttoogood** [comment]
You can install the react-css-modules typings and it works just fine

**Comment by gajus** [comment]
I might be wrong (I don't use TS), but TS and Babel are incompatible.

I do use types, though I use https://flowtype.org/.

In case of the latter, you can strip flow types using https://www.npmjs.com/package/babel-plugin-transform-flow-strip-types transpiler, which becomes part of your build routine.

This is a generic question about Babel and TypeScript. Not relevant to `babel-plugin-react-css-modules`.

**Comment by diegolaciar** [comment]
TS and Babel are compatible, I' m using it without problem  on a react
project.

The issue I have is with babel-plugin-react-css-modules  .I can´t make it
work with this project setup.

**Comment by gajus** [comment]
> The issue I have is with babel-plugin-react-css-modules  .I can´t make it work with this project setup.

Please fork https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo and reproduce the issue. I will re-open the issue.

**Comment by TheXardas** [comment]
Any progress on this issue? :)
