### ISSUE TITLE
Allow empty string to be passed to styleName.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [gajus/babel-plugin-react-css-modules#34]
I have a use case where I conditionally want to apply a style, e.g.

```
<div styleName={isReady : 'ready' : ''}>
  ...
</div>
```

Currently there's no way to accomplish this, because the plugin will explode looking for a CSS module that uses an empty string. Is there a way to short-circuit this case and give up?

**Comment by gajus** [comment]
@AndrewSouthpaw fixed.

**Comment by AndrewSouthpaw** [comment]
Thanks! I'm trying to download v2.1.4, but npm is saying it's invalid...

**Comment by gajus** [comment]
> Thanks! I'm trying to download v2.1.4, but npm is saying it's invalid...

Can you share the error log?

**Comment by AndrewSouthpaw** [comment]
Weird, it fixed itself. :-/
