### ISSUE TITLE
"babel-plugin-react-css-modules" is an invalid tag on StackOverflow

### ISSUE THREAD

**Issue by max-nova** [gajus/babel-plugin-react-css-modules#37]
The initial text in the "New Issue" page for this git repo tells users to "Raise a question on http://stackoverflow.com/ using 'babel-plugin-react-css-modules' tag."  However, this tag doesn't exist on StackOverflow because it is too long (25 char max).

I'd love to get help with an issue I'm having getting "composes" to work!

http://stackoverflow.com/questions/41518465/composes-not-working-with-babel-plugin-react-css-modules

**Comment by gajus** [comment]
<img width="1047" alt="screen shot 2017-01-15 at 17 30 47" src="https://cloud.githubusercontent.com/assets/973543/21964673/6266888e-db48-11e6-9ce0-f2ea45192ab6.png">

Bummer.
