### ISSUE TITLE
Named reference creating unused variables

### ISSUE THREAD

**Issue by mondaychen** [gajus/babel-plugin-react-css-modules#39]
I'm trying to use this plugin in my project. However, I got eslint "no-unused-variables" errors when I import css files and name them as variables.

Any ideas to fix this?

**Comment by tsnieman** [comment]
You could add ```// eslint-disable-line no-unused-variables``` (or something similar) on the end of that line.

For example:
```
@import "styles.css"; // eslint-disable-line no-unused-variables
```

Or somehow modify the rule to ignore all CSS imports (but that seems more involved; I prefer the disable/comment solution above).

**Comment by mondaychen** [comment]
@tsnieman I know how to disable eslint by line. However, it would become pretty annoying if I had to type the comment every time I import more than one css files.

Actually, I would prefer to always use named reference no matter if multiple css files are needed or not. Anonymous reference seems too implicit.

**Comment by gajus** [comment]
> Actually, I would prefer to always use named reference no matter if multiple css files are needed or not. Anonymous reference seems too implicit.

They are entirely predictable, though. Anonymous imports will fail if you try to add more than one import.

**Comment by gajus** [comment]
I am slightly confused what `no-unused-variables` ESLint rule has to do with the use of this plugin. You can simply disable the ESLint rule locally, if thats what you want.

**Comment by Nudelsieb** [comment]
@gajus Everytime I use named imports of CSS files the console gets spammed with lint warnings of 'no-unused-vars', like mentioned above. I don't want to switch off the rule in my '.eslintrc' because it is very useful. Is there a way of ignroing the rule only for CSS modules?

**Comment by gajus** [comment]
> @gajus Everytime I use named imports of CSS files the console gets spammed with lint warnings of 'no-unused-vars', like mentioned above. I don't want to switch off the rule in my '.eslintrc' because it is very useful. Is there a way of ignroing the rule only for CSS modules?

Whats the reason you are importing variable in the first place?

I am assuming you are doing ~:

```js
import styles from './styles.css';

```

Instead of doing that, just do:

```js
import './styles.css';

```

If you are using named `styleName` resolution (https://github.com/gajus/babel-plugin-react-css-modules#named-stylename-resolution), then I cannot think of a solution other than writing an ESLint plugin that silences these errors if style reference is detected in `styleName` attribute.

**Comment by Nudelsieb** [comment]
Thanks, I solved it by using className and string literals, e.g.

```
import style from 'style.scss';

<div className={`${style['selector-one']} ${style.selectorTwo}`}>
...
</div>
```

**Comment by IanVS** [comment]
If anyone makes or finds an eslint plugin to silence these, please post it up here. It would be useful.

**Comment by didi0613** [comment]
I have the same problem here, when i was trying to import multiple files as
```
import custom from "../styles/custom.css";
import milligram from "milligram/dist/milligram.css";
```

```
<div styleName={"custom.docs-example"}>
      <a styleName={"milligram.button milligram.button-outline"} href="#">
        Anchor button
      </a>
</div>
```

eslint would still prompts errors as: 
```
1:8  error  'custom' is defined but never used     no-unused-vars
2:8  error  'milligram' is defined but never used  no-unused-vars
```

Please provide some ideas here.

**Comment by gajus** [comment]
> Please provide some ideas here.

```js
// eslint-disable-next-line no-unused-vars
import custom from "../styles/custom.css";
// eslint-disable-next-line no-unused-vars
import milligram from "milligram/dist/milligram.css";

```
