### ISSUE TITLE
Cannot use styleName attribute without importing at least one stylesheet

### ISSUE THREAD

**Issue by craigcosmo** [gajus/babel-plugin-react-css-modules#41]
I got this error since updating to version 2

<img width="967" alt="screen shot 2017-01-12 at 1 41 40 am" src="https://cloud.githubusercontent.com/assets/538657/21861649/4ff877d0-d868-11e6-876f-2f917b572308.png">

reproducing: https://github.com/craigcosmo/react-css-module-bug

**Comment by cyl19910101** [comment]
Looks like the version 2 can not use the same config and version 1 at least on sass? 

`import style from './post.scss';` this import would get an error "CSS module import does not exist." on 2.1.4, while the same code works well on 1.2.0

The plugin config in babelrc :
`[
      "react-css-modules",
      {
        "generateScopedName" : "[name]__[local]___[hash:base64:5]"
      }
    ]`

and the loaders in webpack.config file :
`{
        test   : /\.(css|scss)$/,
        loader : ExtractTextPlugin.extract ( 'style?sourceMap',
          'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          'sass?sourceMap'
        )
      }`


Another thing I wanna get some help is the absolute path import of style files, 

This config in webpack.conf :
`resolve : {
    extensions : [ '', '.js', '.scss', '.css' ]
    , root     : [ root ]
  },`
make .js file import url works correctly, when I do `import 'nav/logo'`, the webpack will try to get file store in [root]/nav/logo, however this doesn't work when I do import a style file (neither css nor scss), sorry this maybe not relate to this issue.......

Thanks a lot for any help in advance!!!!

**Comment by souporserious** [comment]
Getting the same error trying to use this with Sass :( would love to be able to use `styleName` with Sass if possible.

**Comment by gajus** [comment]
Please follow the instructions at https://github.com/gajus/babel-plugin-react-css-modules#configurate-syntax-loaders. Report back if it does not work.

**Comment by craigcosmo** [comment]
like this?

```json
"babel": {
		"presets": [
			"es2015",
			"react",
			"stage-0"
		],
		"env": {
			"production": {
				"plugins": [
					"transform-remove-console"
				]
			}
		},
		"plugins": [
			["filetypes", 
				{
			  		".scss": "postcss-scss"
				}
			],
			"transform-decorators-legacy",
			"transform-flow-strip-types",
			[
				"react-css-modules",
				{
					"generateScopedName": "[local]___[hash:base64:5]"
				}
			],
			[
				"react-intl",
				{
					"messagesDir": "./translation/defaultMessage",
					"enforceDescriptions": false
				}
			]
		]
	}
```

I got error:

```
ReferenceError: Unknown plugin "filetypes" specified in "/Users/craigcosmo/Dropbox/Code/thatilike front/package.json" at 0, attempted to resolve relative to "/Users/craigcosmo/Dropbox/Code/thatilike front"
```

**Comment by gajus** [comment]
`filetypes` needs to be an option of `react-css-modules` plugin.

**Comment by craigcosmo** [comment]
ok, just wondering why we didn't need this config when using version 1.x?

**Comment by gajus** [comment]
Because it was baked in.

The reason it was baked in is because I arrogantly assumed that everyone is using SASS. When the reality is that there are many different flavours of CSS.

The present setup enables use of `babel-plugin-react-css-modules` with any flavour that is available as postcss loader.

**Comment by cyl19910101** [comment]
Thanks a lot, with filetypes configured, it worked! Do you have ideas about how to config the "root" for this plugin? Setting `resolve.root` won't make it work.

**Comment by gajus** [comment]
> Thanks a lot, with filetypes configured, it worked! Do you have ideas about how to config the "root" for this plugin? Setting resolve.root won't make it work.

See `context` configuration.

https://github.com/gajus/babel-plugin-react-css-modules#configuration

**Comment by cyl19910101** [comment]
Yes, I did it, as I mentioned above, I set it with `"context" : "./src"`, I don't know the correct way to set the `context` value, I've tried add the `context` to webpack.config.js according to [https://webpack.github.io/docs/configuration.html#context](url) --

```
const path              = require ( 'path' );
const ExtractTextPlugin = require ( 'extract-text-webpack-plugin' );
const root              = path.resolve ( './src' );
const dist              = path.resolve ( './dist' );

const config = {
  entry   : `${root}/index.js`,
  output  : {
    filename : 'bundle.js',
    path     : dist
  },
  context : root,
  module  : {
    loaders : [
      {
        test   : /\.(css|scss)$/,
        loader : ExtractTextPlugin.extract ( 'style?sourceMap',
          'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]',
          'sass?sourceMap'
        )
      },
      {
        test    : /\.js$/,
        loader  : 'babel-loader',
        exclude : /node_modules/
      }
    ]
  },
  resolve : {
    extensions : [ '', '.js', '.scss', '.css' ]
    , root     : [ root ]
  },
  plugins : [
    new ExtractTextPlugin ( "styles.css" )
  ]
};

module.exports = config;
```
as well as the .babelrc  --

```
{
  "presets" : [
    "es2015",
    "react"
  ],
  "plugins" : [
    [
      "react-css-modules",
      {
        "context"            : "./src",
        "generateScopedName" : "[name]__[local]___[hash:base64:5]",
        "filetypes"          : {
          ".scss" : "postcss-scss"
        }
      }
    ]
  ]
}

```

With the config above it doesn't work, would you mind give me an example config of this `context` field, Thank you very much!

**Comment by gajus** [comment]
`context` must be an absolute path.

**Comment by gajus** [comment]
I cannot think of a way to configure it using `.babelrc`. You need to provide `babel-loader` configuration via webpack configuration file.

**Comment by moimikey** [comment]
just for reference, this will be possible in babel 7, as you'll be able to use `.babelrc.js`

**Comment by antoniobrandao** [comment]
@gajus Would be great if you had an example already configured with SASS/SCSS. Struggling to implement this.

**Comment by Slapbox** [comment]
I would also love an example. I tried the configuration above and I get `Invalid configuration`

```
[ { keyword: 'type',
    dataPath: '.filetypes[\'.scss\']',
    schemaPath: '#/properties/filetypes/patternProperties/%5C..*/type',
    params: { type: 'object' },
    message: 'should be object' } ]
```

**This is my plugins section in my .babelrc:**

"plugins": [
    "add-module-exports",
    "dynamic-import-webpack",
    "transform-remove-console",
    "transform-remove-debugger",
    "minify-mangle-names",
    [
        "react-css-modules",
        {
          "generateScopedName": "[local]___[hash:base64:5]",
          "filetypes": {
            ".scss": "postcss-scss"
          }
        }
    ]
  ],
```

**Comment by blackLearning** [comment]
@Slapbox add syntax
```js
[
                  'react-css-modules',
                  {
                    generateScopedName: '[local]__[hash:base64:7]',
                    filetypes: {
                      '.less': {
                        syntax: 'postcss-less'
                      }
                    }
                  }
                ],
```

**Comment by vikasraj789** [comment]
@gajus 
Is it needed to import the stylesheets in each file to use them? Currently it works only if I import the file. Else "CSS module import does not exist" error is thrown.

**Comment by targumon** [comment]
`".scss": "postcss-scss"`
gives an 'Invalid configuration'. I'm new to this so I don't know if it used to work.
Fixed it with this:
`".scss": {"syntax": "postcss-scss"}`
Hope this helps others :-)

**Comment by tangsauce** [comment]
After hours, finally got this to work:

```
/* App.jsx */

import React from 'react'

import css from './styles/base.css'
import scss from './styles/base.scss'
import sass from './styles/base.sass'

class App extends React.Component {
  constructor(props) {
    super(props)
    console.log('css', css)
    console.log('scss', scss)
    console.log('sass', sass)
  }
  render() {
    return (
      <div>
        <div styleName='css.yellow'>styleName css</div>
        <div styleName='scss.red'>styleName scss</div>
        <div styleName='sass.blue'>styleName sass</div>
      </div>
    )
  }
}

export default App

```

```
/* webpack.config.js */


module.exports = () => {
  return {
    entry: './src/index.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'bundle.js',
    },
    mode: 'development',
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env', '@babel/preset-react'],
              plugins: [
                [
                  'react-css-modules',
                  {
                    "filetypes": {
                      ".scss": { "syntax": "postcss-scss" },
                      ".sass": { "syntax": "postcss-sass" },
                    }
                  }
                ],
              ],
            },
          },
        },
        {
          test: /\.(sa|sc|c)ss$/,
          use: [
            devMode
            ? { loader: 'style-loader', options: { sourceMap: true } }
            : { loader: MiniCssExtractPlugin.loader, }
            ,
            { loader: 'css-loader',
              options: {
                modules: true,
                sourceMap: true,
                localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
                importLoaders: 1,
              }
            },
            {
              loader: "sass-loader",
              options: {
                sourceMap: true,
              }
            }
          ]
        },
      ]
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new MiniCssExtractPlugin({
        // Options similar to the same options in webpackOptions.output
        // both options are optional
        filename: "[name].css",
        chunkFilename: "[id].css"
      })
    ],
    devServer: {
      contentBase: path.resolve(__dirname, 'dist'),
      hot: true,
    },
    devtool: 'source-map',
    // resolve: {
    //   extensions: [],
    //   alias: {
    //     '~': path.resolve(__dirname, './src')
    //   }
    // },
  }
}
```

An example with scss/sass/less, etc. should really be in the official docs...
