### ISSUE TITLE
`composes: x from 'path';` not working.

### ISSUE THREAD

**Issue by amsayk** [gajus/babel-plugin-react-css-modules#43]

**Comment by gajus** [comment]
@amsayk Is there an issue here or is this a non-issue?

**Comment by tsnieman** [comment]
@gajus Looks like they were trying to achieve something like #46 (use webpack module directories / "resolve aliases"). In particular, it seems like @amsayk was trying to use `composes` with those aliases (which doesn't work even if you configure PostCSS import plugin for aliases -- see my comment [here](https://github.com/gajus/babel-plugin-react-css-modules/issues/46#issuecomment-286584845)).
