### ISSUE TITLE
'undefined' className

### ISSUE THREAD

**Issue by chrisvasz** [gajus/babel-plugin-react-css-modules#45]
```js
// message.js
import './message.css';
function Message(props) {
  return <div className={props.className} styleName="message">message</div>;
}
render(<Message />);
```
```js
// output from Babel with babel-plugin-react-css-modules
import './message.css';
function Message(props) {
  return <div className={props.className + ' message___3Hgmr'}>message</div>;
}
render(<Message />);
```

This outputs a div with `className="undefined message___3Hgmr"` because `props.className` is `undefined`.

A more robust output might look something like this:
```js
// better output
import './message.css';
function Message(props) {
  return <div className={(props.className ? props.className + ' ' : '') + 'message___3Hgmr'}>message</div>;
}
render(<Message />);
```

**Comment by gajus** [comment]
I see.

I am not convinced that the overhead (ah additional IF conditional for each variable used in class declaration) is worth the fix. Of course, if the stylesheet includes "undefined" class, this will produce unexpected results.

This could be something thats enabled only in `NODE_ENV=development`.

**Comment by CurtisHumphrey** [comment]
PR: https://github.com/gajus/babel-plugin-react-css-modules/pull/62
