### ISSUE TITLE
Support for Webpack resolve aliases

### ISSUE THREAD

**Issue by mikeycgto** [gajus/babel-plugin-react-css-modules#46]
Is it possible to support webpack resolve aliases?

I prefer to use alias rather than have to import off relative paths.

**Comment by guoerwei** [comment]
+1

**Comment by moorthy-g** [comment]
Yes, It'd be helpful

**Comment by tsnieman** [comment]
You can achieve resolve aliases except for `composes` via [this method](https://github.com/gajus/babel-plugin-react-css-modules/issues/49#issuecomment-286541152) of using a PostCSS import plugin which supports aliases.

Haven't looked into trying to get `composes` working with the same aliases though (i.e. so those still have to `../be/relative/imported.css`)

**Comment by andrewboot** [comment]
You can just use postcss plugin 'postcss-import' and configure it for resolving your modules in `postcss.config.js`:

```
const importLoader = require('postcss-import')({
  extension: '.scss', // default is '.css'
  resolve: (id) => {
    if (id === 'SharedCSS') return path.resolve(currentPath, './sources/css/_variables.scss');
    return id;
  },
});
```


and then use it like that:

`@import "MyCSSVariables"`

in every file needs access to the variables

Hope it helps!

**Comment by toc777** [comment]
Is there any plan to work on this? I'd love to use this plugin over react-css-modules but I use a lot of webpack aliases. Is it possible to use the babel module resolver instead of require.resolve? If so, I could potentially use another babel-resolver plugin to set up the aliases.

**Comment by gajus** [comment]
No plans to support custom resolve paths.

**Comment by moimikey** [comment]
bit of a terrible blocker to be honest... what's it take for a contributor to add support for this? is it feasible/possible?

**Comment by hankthewhale** [comment]
Bummer. Without a solution to somehow resolve `composes: flex from 'shared_styles/flex-layout.css'; where 'shared_styles' is a webpack alias, this will block us from moving to this lib.

**Comment by danny-andrews** [comment]
@moimikey I'd recommend switching over to using css-modules directly via the https://github.com/webpack-contrib/css-loader. It works fine with webpack aliases.

**Comment by CoralSilver** [comment]
I'd like support for this as well if possible.

**Comment by moimikey** [comment]
@danny-andrews went right above my head. thanks.

**Comment by bhavyaw1** [comment]
+1 

Is there any plan to support this?

**Comment by gneu77** [comment]
@gajus you wrote "No plans to support custom resolve paths". Does this just mean you don't plan to support the webpack resolve aliases (which I could totally understand), or do you even mean you don't plan to add an alias option for babel-plugin-react-css-modules on its own?

**Comment by gneu77** [comment]
I mean you could feature a resolve option like this for config in babelrc:
`['babel-plugin-react-css-modules', {
      'generateScopedName': '[name]---[local]---[hash:base64:5]',
      'resolve': { '@styles': path.resolve(__dirname, 'src/styles') }
 }]`

Currently, I have a lot of imports like this:
`import colors from '../../../../../../styles/colors.css'`
and I'd be really happy to somehow replace them by e.g.:
`import colors from '@styles/colors.css'`

**Comment by gajus** [comment]
> Currently, I have a lot of imports like this:
> import colors from '../../../../../../styles/colors.css'
> and I'd be really happy to somehow replace them by e.g.:
> import colors from '@styles/colors.css'

I would not support this either.

Doing this is just asking for a trouble.

It is perfectly normal to have multiple levels of nesting in a project. The particular example (`../../../../../../`) seems a bit excessive, but thats a problem with the project's file tree structure. Adding aliases is just a workaround disguising the underlying problem.

Besides, you can easily add the suggested feature with a separate babel plugin. It does not need to be part of `babel-plugin-react-css-modules`.

**Comment by AndreasCag** [comment]
Just add babel-plugin-module-resolver and you can easily achieve this feature.


```js
module.exports = {
  ...
  "plugins": [
    ...
    ["module-resolver", {
      "alias": {
        "@": path.join(__dirname, 'src'),
      }
    }]
  ],
};

```
