### ISSUE TITLE
Make unknown styles silently be ignored

### ISSUE THREAD

**Issue by aikar** [gajus/babel-plugin-react-css-modules#47]
When a class name is missing, it would be better if it simply did not add a class to the class list instead of failing.

This makes it hard to dynamically generate class names when iterating an array to ALLOW for targeting IF needed. 

But as it stands now, you would have to define every possible class in the array in the style sheet as it's a hard failure if it doesn't find it.

This doesn't fit with what people expect of CSS.

**Comment by bjudson** [comment]
I disagree. It is useful to quickly discover when you have mistyped a class name, or accidentally put a global `className` into the `styleName` prop. One thing I like about this system is that it fits more with what I expect of a module system than what I expect of CSS (global definitions, silent failure).

**Comment by bearcott** [comment]
I agree. When I work, I will often save my html files without the class names first and then add them in later. With this plugin my server will break because of this and I have to restart it because its a babel error.

**Comment by aikar** [comment]
@bjudson there could be an option for those who want a hard failure.

Though id like to amend my request to just say add the class naked, no remapping.

Then would be good if this plugin by default added normal AND the modularized version.

**Comment by aikar** [comment]
closing as i see you can now reduce missing modules to warnings instead of hard failures.
