### ISSUE TITLE
Nested styles don't work

### ISSUE THREAD

**Issue by aevk** [gajus/babel-plugin-react-css-modules#49]
An example
```css
.nav {
  &-item {
    color: red;
  }
}
```
```
...
  Module build failed: Error: /path/to/my/component.js: CSS module does not exist.
...
```

I solved this problem by installing **postcss-nested** in
```
  /path/to/myproject/node_modules/babel-plugin-react-css-modules/
 ```
and added in [requireCssModule.js](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/requireCssModule.js) 
```javascript
...
import ExtractImports from 'postcss-modules-extract-imports';
import LocalByDefault from 'postcss-modules-local-by-default';
import Parser from 'postcss-modules-parser';
import Scope from 'postcss-modules-scope';
import Values from 'postcss-modules-values';
import Nested from 'postcss-nested'; // add
...
const plugins = [
  Nested, // add (before or after Values)
  Values,
  LocalByDefault,
  ExtractImports,
  new Scope({
    generateScopedName: scopedName
  }),
  new Parser({
    fetch
  })
];
...
```
And all works well. But it would be nice to have native support.

**Comment by gajus** [comment]
@aevk Can you raise a PR please?

**Comment by richchurcher** [comment]
Thanks @aevk that was bugging me too! Thanks to @gajus for the excellent work :)

**Comment by gajus** [comment]
Sorry, I've misinterpreted the original issue.

The nested styles are not supposed to work out of the box: it is not part of the CSS standard. You can use a CSS preprocessor, e.g. https://github.com/postcss/postcss#syntaxes

**Comment by tsnieman** [comment]
@aevk I use my own PostCSS plugins and have no problem with nesting. Just make sure your style loaders and PostCSS plugins are configured properly. For example:

[`postcss.config.js`](https://github.com/tsnieman/webpack2test/blob/2a20f2cd299d5c750448fa188978ff5333a81042/postcss.config.js#L18-L26)
```
module.exports = {
  // Note that PostCSS plugin ordering is important.
  plugins: [
    require('postcss-nested')(),
    require('postcss-import')({
      path: [
        './src'
      ],
    }),
    require('postcss-custom-properties')(),
    require('postcss-color-function')(),
    require('autoprefixer')({ browsers: ['last 2 versions'] }),
  ]
}
```

:sparkles:

**Comment by richchurcher** [comment]
Yes, I forgot not everyone would be using SASS etc with this plugin! Thanks for the suggestions, I'll follow those up.

**Comment by levity** [comment]
@gajus -- to be clear, my issue in #71 is that even if you *are* using the `postcss-scss` preprocessor, [nested styles are still not supported](https://github.com/postcss/postcss-scss/issues/56).

@tsnieman, when you define your own postcss.config.js this way, how does it interact with the list of postcss plugins that babel-plugin-css-modules sets up in [requireCssModule.js](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/src/requireCssModule.js#L80)? Does it prepend, append, override, etc.?

**Comment by tsnieman** [comment]
@levity `babel-plugin-react-css-modules` is set up so that it mimics basic CSS (with some special css module stuff sprinkled on). Hence, no nesting; nesting would be outside the scope of this project.

> when you define your own postcss.config.js this way, how does it interact with the list of postcss plugins that babel-plugin-css-modules sets up in requireCssModule.js? Does it prepend, append, override, etc.?

I assume it appends (rather than over-rides). Reasoning: the `LocalByDefault` plugin is included as a default in `requireCssModule.js`, as it provides a good CSS Modules default. Since AFAIK mine are local by default, and since I don't include that plugin in my own PostCSS config, I assume it appends.

**Comment by levity** [comment]
I understand that nesting is outside the scope of the project. I'm not suggesting that `postcss-nested` be included by default, only that an option should be provided to add it, just as an option is provided to allow `postcss-scss`, because if someone wants to use this plugin with Sass, they will need both.

**Comment by tsnieman** [comment]
> I'm not suggesting that postcss-nested be included by default, only that an option should be provided to add it

Is this "option" not just using `postcss.config.js`? I use `postcss-nested` in my postcss.config.js -- along with several other plugins. I could add `postcss-scss` to the end and it would be used too. The point of PostCSS is to more-or-less build your own flavor of CSS which means that plugins (`postcss-scss` included) might not be every bit of functionality you need. Just add more plugins :+1:

**Comment by levity** [comment]
Isn't `postcss.config.js` specific to webpack? I'm not using it for server-side rendering...

**Comment by levity** [comment]
Fair enough I suppose -- I guess as a relatively new PostCSS user I didn't realize that config file existed, and was just looking at the docs for this plugin for options.

**Comment by levity** [comment]
Does that config file work without webpack?

**Comment by gajus** [comment]
> Fair enough I suppose -- I guess as a new PostCSS user I didn't realize that config file existed, and was just looking at the docs for this plugin for options.

Once you've figured it out, it would be a useful PR to document how-to for others who might be seeking for it.

**Comment by levity** [comment]
I couldn't get it to work without webpack. :(

**Comment by tsnieman** [comment]
> Does that config file work without webpack?

I imagine the config is used by [`postcss-loader`](https://github.com/postcss/postcss-loader) which I've only ever used via Webpack.

**Comment by nemoisfree** [comment]
i have some problem. how to enable postcss-nested in webpack config with babel-plugin-react-css-modules

**Comment by levity** [comment]
@nemoisfree -- the short answer is that you want babel-loader and postcss-loader, and then add postcss-nested as one of your plugins in postcss-loader. Hope that helps.
