### ISSUE TITLE
Unknown prop `styleName` on <div> tag. 

### ISSUE THREAD

**Issue by regenrek** [gajus/babel-plugin-react-css-modules#5]
Hi,

I get the same error on this repository. Is this related?

https://github.com/gajus/react-css-modules/issues/147

**Comment by ksrb** [comment]
@regenrek sounds like your webpack config isn't correct? I have a pretty [minimalistic config](https://github.com/ksrb/babel-plugin-react-css-modules-test) that works if you want to take a look.

**Comment by regenrek** [comment]
@ksrb Oh yeah didn't implement the plugin in the .babelrc.

Thank you!

**Comment by ksrb** [comment]
If someone run into this issue at a later date there is now a official demo in the repo https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo.
