### ISSUE TITLE
can there be better error handling?

### ISSUE THREAD

**Issue by craigcosmo** [gajus/babel-plugin-react-css-modules#50]
I have jsx like this

```js
<div styleName="home">
	<div styleName="header">
	</div>
</div>
```

if I have missing class `.header` in my stylesheet, I will will get very generic error. I have no idea that I'm missing `.header`. Is there way to specify which class is missing?

**Comment by gajus** [comment]
Addressed in https://github.com/gajus/babel-plugin-react-css-modules/pull/56
