### ISSUE TITLE
Feature Request: Ability to ignore node_modules

### ISSUE THREAD

**Issue by fracmak** [gajus/babel-plugin-react-css-modules#52]
I currently use react-css-modules for local components, but still use webpack's style loader for theme/widget stylesheets loaded in node_modules. This plugin tries to parse those libraries and bomb. It would be great to pass in a file pattern to ignore (similar to the condition syntax of webpack: https://webpack.js.org/configuration/module/#condition )

**Comment by gajus** [comment]
PR welcome.

**Comment by CurtisHumphrey** [comment]
PR: https://github.com/gajus/babel-plugin-react-css-modules/pull/61

**Comment by efosao** [comment]
This issue can closed since PR #61 has been merged into master, and the config now support and 'exclude' option which takes a string (e.g. 'node_modules').
