### ISSUE TITLE
Wrong Installation instructions for demo

### ISSUE THREAD

**Issue by steven-fernandez** [gajus/babel-plugin-react-css-modules#53]
I'm trying to test the demo on this page:

`https://github.com/gajus/babel-plugin-react-css-modules/tree/master/demo`

So, I created a new folder and from the console I first this:

`git clone git@github.com:gajus/babel-plugin-react-css-modules.git ` 

This give me this error:

_Permission denied (publickey).
fatal: Could not read from remote repository._

Please make sure you have the correct access rights
and the repository exists.

So, to bypass this error I just manually download the zip file and extract the demo folder.

Next I run ... npm install 

This one goes well ...

And finally I run:

`webpack-dev-server `

and I get:

command not found 

What are the right instructions to run the demo?

**Comment by callil** [comment]
Hey Steven, I got this to work by running `npm install webpack-dev-server -g`  I think this needs to be added as a dependency because some people might not have this installed in their system

**Comment by aikar** [comment]
@steven-fernandez this is actually your problem: https://github.com/gajus/babel-plugin-react-css-modules/pull/54

You don't have SSH keys setup on your GitHub.

**Comment by aikar** [comment]
Also, you would need to npm install -g webpack-dev-server
