### ISSUE TITLE
Unknown props in Enzyme/Jest

### ISSUE THREAD

**Issue by yangyu0311ugroop** [gajus/babel-plugin-react-css-modules#70]
Not sure if this is the old questions. 

```
import React from 'react';
import './table.css';

export default class Table extends React.Component {
  render () {
    return <div styleName='table'>
      <div styleName='row'>
        <div styleName='cell'>A0</div>
        <div styleName='cell'>B0</div>
      </div>
    </div>;
  }
}
```

As the example posted, this works great, but if I want to test this table, by using 
```
const component = shallow(<Table />);
component.html();
```
I get unknown styleName props console warning. I wonder is there any ways to mute this warning apart from stripping down prop name by using spread operator.

Thanks

**Comment by gajus** [comment]
> I get unknown styleName props console warning. I wonder is there any ways to mute this warning apart from stripping down prop name by using spread operator.

Are you sure that `babel-plugin-react-css-modules` plugin is being used?

`babel-plugin-react-css-modules` is supposed to "strip" the `styleName` property.

**Comment by yangyu0311ugroop** [comment]
@gajus it only happens in the testing code, the dev/production works fine. I follow the example from the demo application. Do I need to configure something else? 
For example, this is one of my component

```
function FormControl({ className, ...props }) {
  const edited = props.value && 'edited';
  return (
    <div {...props} styleName={`${className} ${edited}`} />
  );
}
```

In my testing code. 
```
describe('<FormControl />', () => {
   const renderedComponent = shallow(
    <FormControl value={value} className='testClass' />
  );
  it('should exists', () => {
    expect(FormControl);
  });
});
```
The renderedComponent will produce the html like this below. It passes the test but it will also give me the warning of unknown props. 
```
<div value="" styleName="testClass " />
```
```
Warning: Unknown props `inputRef`, `styleName` on <div> tag. 
Remove these props from the element. For details, see https://fb.me/react-unknown-prop
        in div
        in FormControl 
```

**Comment by gajus** [comment]
You haven't answered the question – is the test environment configured to use `babel-plugin-react-css-modules`? I am assuming you might have different settings depending on the environment in your `.babelrc`.

**Comment by yangyu0311ugroop** [comment]
@gajus You are right, I haven't setup the testing environment properly. Thank you for pointing out the direction.

**Comment by samsamai** [comment]
Do you mind sharing your test environment config, as I'm having the same issue.

**Comment by yangyu0311ugroop** [comment]
@samsamai I didn't use ```.babelrc```, but instead I put it inside package.json. Hope it helps

```
 "babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs",
          "dynamic-import-node",
          [
            "react-css-modules",
            {
              "generateScopedName": "[local]"
            }
          ]
        ]
      }
    }
  },
```
