### ISSUE TITLE
How to add postcss-nested?

### ISSUE THREAD

**Issue by levity** [gajus/babel-plugin-react-css-modules#71]
I am trying to use this plugin with .scss files which contain nesting, e.g.:

```scss
.foo {
  &-bar {
    // so that I can do styleName='foo-bar' in a component
  }
}
```

`postcss-scss` doesn't handle this, though; it seems I need to add `postcss-nested`. How can I do this?

**Comment by levity** [comment]
Confirmed that this works if I prepend postcss-nested to the list of plugins for the postcss instance. I can make a PR if this seems useful to you. If so, what would you want to name the option?

**Comment by tsnieman** [comment]
Hey @levity -- someone has opened an issue for this before; you should be able to find a solution here: gajus/babel-plugin-react-css-modules/issues/49

**Comment by gajus** [comment]
Closing as duplicate.

Thank you @tsnieman

**Comment by levity** [comment]
Thank you, sorry I missed that!
