### ISSUE TITLE
Support array of styles

### ISSUE THREAD

**Issue by damianobarbati** [gajus/babel-plugin-react-css-modules#76]
Can we pass array of styles? Working with string concatenation is crappy and does not properly work in this scenario.

```
import commonStyles from '../global.scss';
import styles from './component.scss';

<div styleName={[commonStyles.first, commonStyles.second, styles.third]} />

<div styleName={[commonStyles.first, commonStyles.second, styles.third].join( } /> //does not work
```

**Comment by gajus** [comment]
Whats the reason you are not simply using `className`?

```js
<div className={[commonStyles.first, commonStyles.second, styles.third]} />
```

should work.

**Comment by damianobarbati** [comment]
@gajus no it's not!

**Comment by gajus** [comment]
Just add `.join(' ')`.

**Comment by damianobarbati** [comment]
@gajus thanks, that's what I'm doing right now... but the goal is to avoid that! xD
It's kinda boring to add to every piece of code this .join(' ') or classnames().
It seems to be a widely used functionality, why not integrate it?

**Comment by gajus** [comment]
> It seems to be a widely used functionality, why not integrate it?

It is not. In CSS module land, class composition is predominant strategy to style elements depending on their state.

https://github.com/gajus/react-css-modules#class-composition

**Comment by damianobarbati** [comment]
@gajus this has nothing to do with "class composition": classes are going to be defined like that anyway, we're talking about applying them without repeating code i.e: `.join(' ')`

**Comment by damianobarbati** [comment]
how are you applying multiple classes to a component right now?

**Comment by dex-labs** [comment]
Seems like this still hasn't been implemented. 

Would be helpful to not have to always add .join(' ')
