### ISSUE TITLE
Can't import css from node_modules

### ISSUE THREAD

**Issue by fracmak** [gajus/babel-plugin-react-css-modules#8]
when doing something like `import 'some-module/my.css';` babel plugin crashes with a message saying it can't find `__dirname/some-module/my.css` when it should be looking in ~/node_modules/some-module/my.css`

This is functionality that worked using ReactCSSModules

**Comment by gajus** [comment]
Can you have a look into version v1.1.1 and see if you can replicate the issue?

If you can, can you please raise a PR with a fix or a failing test case?

**Comment by jmcclell** [comment]
@gajus I'm having the same problem. Here is a stripped down project exhibiting the symptom:
https://github.com/jmcclell/babel-plugin-react-css-modules-testcase

**Comment by gajus** [comment]
Thank you @jmcclell for reproducing the issue.

It has been fixed now.
