### ISSUE TITLE
Error: Cannot use anonymous style name with more than one stylesheet import

### ISSUE THREAD

**Issue by xenongattz** [gajus/babel-plugin-react-css-modules#80]
I have problem when importing multiple styles:
"Cannot use anonymous style name with more than one stylesheet import."

Code for import is:

```
import pageStyles from './signUp.css';
import calendarStyles from 'rc-calendar/assets/index.css';
let styles = Object.assign({}, pageStyles, calendarStyles);
```

Trying to combine styles but compile fails.

I used this example to solve this problem:
https://github.com/css-modules/css-modules/blob/master/docs/import-multiple-css-modules.md
But it didn't work.

P.S. When I reference to style like pageStyles.regForm or like this it works. But I cannot merge multiple styles in one to use it in default namespace, without any prefixes.

**Comment by gajus** [comment]
> P.S. When I reference to style like pageStyles.regForm or like this it works. But I cannot merge multiple styles in one to use it in default namespace, without any prefixes.

Thats true, you cannot do that. You will need to use named imports or do the import from within the CSS. You can use a CSS preprocessor for that, such as SASS.

**Comment by ratbeard** [comment]
| When a file imports multiple stylesheets, you must use a named reference.
| Have suggestions for an alternative behaviour? Raise an issue with your suggestion.

Is there a technical reason you can't have an anonymous module when adding a second import?  It would make sense to me if  styleNames without a `.` would be looked up in the anonymous module:

```
import './CoolList.css'
import utils from 'Utils.css'

<ol styleName="cool-list utils.unstyled-list">
</ol>
```
