### ISSUE TITLE
Context config will make hash different

### ISSUE THREAD

**Issue by NE-SmallTown** [gajus/babel-plugin-react-css-modules#84]
[The doc](https://github.com/gajus/babel-plugin-react-css-modules#configuration) says "Must match webpack context configuration",and I check the [demo](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js):

```
plugins: [
  'transform-react-jsx',
  [
    'react-css-modules',
    {
      context: path.resolve(__dirname, 'src')
    }
  ]
]
```

But in my project,I can't set context,if I do that,the result is the last hash of the class attribute of html tag is different with the css file.i.e. the class maybe is `components__Foo__wrap__EKH12` but the css file's class is  `components__Foo__wrap__J69NF` or else.

And in my project,the webpack.config.js is not the same directory with src folder,i.e. :

```
--- config
  --- webpack.config.js
--- src
  --- components
  --- ....

```

So I set the context to `path.resolve(__dirname, '../src')` in the webpack.config.js.But I think this is not the reason which cause the hash different.If I don't set the context param,everything works fine(i.e. the context must be `process.cwd()`).

**Comment by gajus** [comment]
> If I don't set the context param,everything works fine(i.e. the context must be process.cwd()).

It it works, thats a coincidence. It will break if you run the build command from a different context.

You must configure `context` in webpack and in plugin options (it must be an absolute value).

**Comment by NE-SmallTown** [comment]
Thanks for you reply,could you tell me why you set context to `path.resolve(__dirname, 'src')` in your demo and it works fine and in my project it can't?

**Comment by gajus** [comment]
As long as you've configured the context of the webpack:

* https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js#L7; and context of the plugin
* https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js#L28

and your actual app resides in that path, it should work. If not then (a) this is a bug [I'd need to see the repository] or (b) you have another transformation in your pipeline thats taking precedence and effects the resulting paths.

**Comment by NE-SmallTown** [comment]
Sorry for the lated response,I will check the pipeline first though I think it is ok,and then if not,I will provide a reproducible demo.

**Comment by Darcrandex** [comment]
but it doesn't work on 'create-react-app v2.1.1'.
