### ISSUE TITLE
Configuration option to add attribute for e2e testing with non-mangled className together with generated from css modules

### ISSUE THREAD

**Issue by alexk0ch** [gajus/babel-plugin-react-css-modules#86]
Hi, 

there is a single case related to e2e testing, when we need to add some static attribute to node to be actually able to query it from e2e driver. 

f.e.: 
`
<MyComponent myProp="myValue" 
                            styleName="myComponentStyle" 
                            dataHook="myComponent" />
`

This `dataHook` is boring to add, and it does nothing in application and only needed for tests, because of no static className generated from cssModules (while usually you can use cssClass as a data hook). 

I'd like to request an additional configuration option to keep the original className, or to generate another one, which will be static and predictable. This can be original className or some combination of component name and className, like `dataHook="MyComponent:myComponentStyle"`; it should be configurable similar to what you already have for className generation, f.e. we should be able to use just a local className: `[local]` and pick attribute name. 

WDYT? 

Thank you!

P.S. We know we can use different configuration for e2e test f.e. and change they way classNames are generated, but we would really like to keep it the same.

**Comment by gajus** [comment]
> P.S. We know we can use different configuration for e2e test f.e. and change they way classNames are generated, but we would really like to keep it the same.

That was going to be my suggestion, i.e. simply changing the value of [generateScopedName](https://github.com/gajus/babel-plugin-react-css-modules#configuration).

Can you explain whats the reason this approach does not work?

**Comment by alexk0ch** [comment]
Frankly speaking - no)

Thank you for fast reply on this, we should really consider utilizing `generateScopedName` configuration for our needs. 

Thanks for all the hard work!
