### ISSUE TITLE
Conflicts with airbnb babel preset, babel-plugin-transform-es3-property-literals

### ISSUE THREAD

**Issue by pbarbiero** [gajus/babel-plugin-react-css-modules#89]
So I cant figure out what I am doing that causes this, but any runtime uses of classes generates this weird format for me:
```
var _styleModuleImportMap = {
  '\'random-0.5302329839985043\'': {
    '\'offset\'': 'Wrapper_offset_1W5nM',
    '\'full\'': 'Wrapper_full_U8Ofk'
  }
}; 
```

This means to use it, I have to escape-quote my literals in the jsx:
`<div styleName={full ? '\'full\'' : '\'half\''} />`

All I am doing is a simple anon import: `import './Wrapper.css';`

I am using webpack 2.5 and using style-loader -> css-loader, and I have react-css-modules configured in my .babelrc rather than in my webpack configuration.

Any ideas whats causing this? Do I need to show you something else to try to track this down? If it comes down to it I can try to create a minimal repo to reproduce this.

**Comment by gajus** [comment]
How are you using it at the moment?

**Comment by pbarbiero** [comment]
Hopefully I am answering your question. Its hard for me to strip down my current projects but here is the basic configuration:

webpack rule:
```
{
  test: /\.css$/,
  exclude: /node_modules/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        modules: true,
        importLoaders: 1,
        localIdentName: '[name]_[local]_[hash:base64:5]',
      },
    },
  ],
}
```

and my .babelrc:
```
{
  "presets": [
    ["airbnb", {"modules": false}],
    "es2015"
  ],
  "plugins": [
    ["react-css-modules", {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }]
  ],
}
```

Really simple use case:

Component: 
`import './Wrapper.css';`
...
`<div id="current-app" styleName={this.state.showBreadcrumbs ? '\'offset\'' : '\'full\''} />`

Wrapper.css:
```
.offset {
  width: 66%;
  display: inline-block;
}

.full {
  width: 100%;
}
```

And compiled bundle:
```
var _styleModuleImportMap = {
  '\'random-0.5987763917302125\'': {
    '\'offset\'': 'Wrapper_offset_1W5nM',
    '\'full\'': 'Wrapper_full_U8Ofk'
  }
};
```

**Comment by pbarbiero** [comment]
While building a minimal repo to reproduce this, I found out its using .babelrc with the airbnb plugin (instead of just using the react plugin) that causes this to break.

After further narrowing, 
the root issue is this plugin conflicts with `babel-plugin-transform-es3-property-literals`

Causes the issue:
```
{
  "presets": [
    ["airbnb", {"modules": false}],
    "es2015"
  ],
  "plugins": [
    ["react-css-modules", {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }]
  ]
}
```
Does NOT cause the issue:
```
{
  "presets": [
    ["es2015", {"modules": false}],
    "react"
  ],
  "plugins": [
    ["react-css-modules", {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }]
  ]
}
```

**Comment by pbarbiero** [comment]
@gajus in your opinion, do you consider this a bug with you, or is it a bug with `babel-plugin-transform-es3-property-literals`?

**Comment by gajus** [comment]
> @gajus in your opinion, do you consider this a bug with you, or is it a bug with babel-plugin-transform-es3-property-literals?

I am not familiar with `babel-plugin-transform-es3-property-literals?`.

Following the description:

> Ensure that reserved words are quoted in object property keys

And your example:

```js
var _styleModuleImportMap = {
  '\'random-0.5302329839985043\'': {
    '\'offset\'': 'Wrapper_offset_1W5nM',
    '\'full\'': 'Wrapper_full_U8Ofk'
  }
}; 
```

None of those keys are reserved words in ES, afaik. Therefore, I'd raise an issue with `babel-plugin-transform-es3-property-literals`.

**Comment by pbarbiero** [comment]
Closing in favor of https://github.com/babel/babel/issues/5754

**Comment by loganfsmyth** [comment]
This should get re-opened. This is a bug in this plugin, I'd assume here: https://github.com/gajus/babel-plugin-react-css-modules/blob/acbb2e87aee800e66caf698d57afd6824d42c192/src/createObjectExpression.js#L35

Identifiers can't have quotes. If the key is supposed to be a string, it should be `t.stringLiteral(name)`. Because it is an `identifier` it is an invalid AST.

**Comment by pbarbiero** [comment]
Thanks loganfsmyth! 

Pull created and fix confirmed.

**Comment by gajus** [comment]
Thank you @loganfsmyth
