### ISSUE TITLE
Doesn't work with custom Webpack resolve paths

### ISSUE THREAD

**Issue by Linksku** [gajus/babel-plugin-react-css-modules#93]
My Webpack configuration contains this:

```
  resolve: {
    modules: [
      path.resolve('./client'),
      'node_modules',
    ],
  }
```

This allows me to import files without a lot of `../`. However, this plugin doesn't seem to work.

E.g. in the file is `components/Component.js`, this won't work:

`import 'styles/Component.css';`

I get the error "Cannot use styleName attribute without importing at least one stylesheet." This works though:

`import '../styles/Component;`

Importing JS files work as expected.

**Comment by gajus** [comment]
https://github.com/gajus/babel-plugin-react-css-modules/issues/46
