### ISSUE TITLE
Ignore Errors in Testing

### ISSUE THREAD

**Issue by jantonso** [gajus/babel-plugin-react-css-modules#97]
I am trying to write some test code using Jest and Enzyme to test out my components. I would like to be able to test that a proptype warning gets thrown when a prop is invalid, but I'm running into the issue where css modules uses the invalid prop to create the stylenames. Is there anyway to ignore these styleName not found errors in a test environment? I noticed that the react-css-modules has a flag for "errorWhenNotFound".

**Comment by gajus** [comment]
There is no such configuration at the moment,

https://github.com/gajus/babel-plugin-react-css-modules#configuration

**Comment by IanVS** [comment]
I would also like to avoid throwing these errors when in production.  I'd be willing to submit a PR to implement the configuration.  I haven't taken a close look at the code for the project, but do you think it would be a relatively straightforward port from `react-css-modules` @gajus?

**Comment by gajus** [comment]
I would not oppose a configuration that allows to conditionally disable errors about styles.
