### ISSUE TITLE
babelrc example

### ISSUE THREAD

**Issue by nemoisfree** [gajus/babel-plugin-react-css-modules#99]
Hello. How to tune .babelrc file, i didn't find it in documentation. 

my .babelrc not working

"plugins": [["babel-plugin-react-css-modules", {
    "filetypes": "postcss-scss"
  }]]

**Comment by anhuiliujun** [comment]
@nemoisfree I meet the same problem, how to tune .babelrc file

**Comment by gajus** [comment]
@nemoisfree Please share your findings with @anhuiliujun

**Comment by nemoisfree** [comment]
@anhuiliujun @gajus 
try **babelrc** file
`{
            "presets": [
                ["es2015"]
            ],
            "plugins": [
                "transform-react-jsx",
                ["react-css-modules",
                    { "filetypes": {
                        ".scss": "postcss-scss",
                    }}
                ]
            ]
        }`
**or webpack2 config**
[](https://github.com/gajus/babel-plugin-react-css-modules/blob/master/demo/webpack.config.js)

**Comment by Mike-Now** [comment]
This babelrc snippet above throws error:

```
[ { keyword: 'type',
    dataPath: '.filetypes[\'.scss\']',
    schemaPath: '#/properties/filetypes/patternProperties/%5C..*/type',
    params: { type: 'object' },
    message: 'should be object' } ]

```

**Comment by Slapbox** [comment]
Same exact issue as @Mike-Now
